"use client";
import {useEffect,useState} from "react";
import type {Locale} from "@/lib/locales";
const ui:Record<Locale,string[]>={nl:["Wachtwoord vergeten?","Vul je e-mailadres in. We sturen een veilige resetlink.","E-mailadres","Even geduld…","Resetlink sturen →","← Terug naar inloggen","Als er een RankFix-account met dit e-mailadres bestaat, hebben we een resetlink gestuurd. Controleer ook je spam.","Aanvraag mislukt."],en:["Forgot password?","Enter your email address. We’ll send a secure reset link.","Email address","Please wait…","Send reset link →","← Back to sign in","If a RankFix account exists for this email address, we sent a reset link. Please also check your spam folder.","Request failed."],de:["Passwort vergessen?","Gib deine E-Mail-Adresse ein. Wir senden dir einen sicheren Reset-Link.","E-Mail-Adresse","Bitte warten…","Reset-Link senden →","← Zurück zur Anmeldung","Wenn für diese E-Mail-Adresse ein RankFix-Konto existiert, haben wir einen Reset-Link gesendet. Prüfe auch deinen Spam-Ordner.","Anfrage fehlgeschlagen."],fr:["Mot de passe oublié ?","Saisissez votre adresse e-mail. Nous vous enverrons un lien sécurisé.","Adresse e-mail","Veuillez patienter…","Envoyer le lien →","← Retour à la connexion","Si un compte RankFix existe pour cette adresse e-mail, nous avons envoyé un lien de réinitialisation. Vérifiez aussi vos spams.","Échec de la demande."],it:["Password dimenticata?","Inserisci il tuo indirizzo e-mail. Ti invieremo un link sicuro.","Indirizzo e-mail","Attendi…","Invia link →","← Torna all’accesso","Se esiste un account RankFix per questo indirizzo e-mail, abbiamo inviato un link di reimpostazione. Controlla anche lo spam.","Richiesta non riuscita."],es:["¿Olvidaste tu contraseña?","Introduce tu correo electrónico. Te enviaremos un enlace seguro.","Correo electrónico","Espera…","Enviar enlace →","← Volver al inicio de sesión","Si existe una cuenta RankFix para este correo, hemos enviado un enlace de restablecimiento. Revisa también el spam.","La solicitud ha fallado."]};
export default function ForgotPassword(){
 const[email,setEmail]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[language,setLanguage]=useState<Locale>("nl");
 useEffect(()=>{const q=new URLSearchParams(location.search).get("lang") as Locale|null;if(q&&q in ui)setLanguage(q)},[]);const t=ui[language];
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");setError("");try{const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,language})});const d=await r.json();if(!r.ok)setError(d.error||t[7]);else setMessage(d.message||t[6])}catch{setError(t[7])}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#0B1220] px-5 py-12 text-white" lang={language}><div className="mx-auto max-w-md"><a href={"/"+language} className="text-lg font-bold">RankFix <span className="text-emerald-300">AI</span></a><div className="mt-10 rounded-3xl border border-white/10 bg-white/[0.04] p-7"><h1 className="text-3xl font-black">{t[0]}</h1><p className="mt-2 text-sm text-slate-400">{t[1]}</p><form onSubmit={submit} className="mt-7 space-y-4"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={t[2]} autoComplete="email" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/>{message&&<div className="rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-200">{message}</div>}{error&&<div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}<button disabled={busy} className="w-full rounded-xl bg-white px-4 py-3 font-bold text-slate-950 disabled:opacity-50">{busy?t[3]:t[4]}</button></form><a href={"/account?lang="+language} className="mt-5 inline-block text-sm text-emerald-300">{t[5]}</a></div></div></main>;
}