"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import type { Locale } from "@/lib/locales";
import "./report.css";

type Check={key?:string;category?:string;title:string;status:string;severity?:string;message:string;fix?:string;rule_id?:string;issue_id?:string;confidence?:string;evidence?:{details?:string;found?:unknown};points?:number;maxPoints?:number;reasonCode?:"cap_absent"|"needs_js"|"insufficient_pages"|"weak_evidence"|"type_uncertain";impactClaim?:"proven_impact"|"best_practice"|"hygiene";formKind?:"contact"|"appointment"|"booking"|"quote"|"checkout"|"newsletter"|"login"|"search"};
type Scan={id?:string;scanned_url:string;final_url?:string|null;created_at:string;result:any};

const reportText:Record<Locale,{back:string;save:string;title:string;subtitle:string;website:string;scanned:string;loading:string;failed:string;groups:string[];labels:Record<string,string>}>={
 nl:{back:"Terug naar audit",save:"Opslaan als PDF",title:"Volledig scanrapport",subtitle:"Bewijsgericht SEO-, GEO- en sectorrapport",website:"Website",scanned:"Gescand",loading:"Rapport laden…",failed:"Rapport kon niet worden geladen.",groups:["Verbeterpunten","Geslaagde controles","Niet te bevestigen","Niet van toepassing"],labels:{fail:"Fout",warning:"Waarschuwing",pass:"Geslaagd",unable_to_confirm:"Niet te bevestigen",not_applicable:"N.v.t."}},
 en:{back:"Back to audit",save:"Save as PDF",title:"Full scan report",subtitle:"Evidence-based SEO, GEO and sector report",website:"Website",scanned:"Scanned",loading:"Loading report…",failed:"Could not load report.",groups:["Improvements","Passed checks","Unable to confirm","Not applicable"],labels:{fail:"Error",warning:"Warning",pass:"Passed",unable_to_confirm:"Unable to confirm",not_applicable:"N/A"}},
 de:{back:"Zurück zum Audit",save:"Als PDF speichern",title:"Vollständiger Scanbericht",subtitle:"Evidenzbasierter SEO-, GEO- und Branchenbericht",website:"Website",scanned:"Gescannt",loading:"Bericht wird geladen…",failed:"Bericht konnte nicht geladen werden.",groups:["Verbesserungen","Bestandene Prüfungen","Nicht bestätigbar","Nicht zutreffend"],labels:{fail:"Fehler",warning:"Warnung",pass:"Bestanden",unable_to_confirm:"Nicht bestätigbar",not_applicable:"N. z."}},
 fr:{back:"Retour à l’audit",save:"Enregistrer en PDF",title:"Rapport d’analyse complet",subtitle:"Rapport SEO, GEO et sectoriel fondé sur des preuves",website:"Site",scanned:"Analysé",loading:"Chargement du rapport…",failed:"Impossible de charger le rapport.",groups:["Améliorations","Contrôles réussis","Impossible à confirmer","Non applicable"],labels:{fail:"Erreur",warning:"Avertissement",pass:"Réussi",unable_to_confirm:"Impossible à confirmer",not_applicable:"N/A"}},
 it:{back:"Torna all’audit",save:"Salva come PDF",title:"Report completo della scansione",subtitle:"Report SEO, GEO e di settore basato su evidenze",website:"Sito",scanned:"Scansionato",loading:"Caricamento report…",failed:"Impossibile caricare il report.",groups:["Miglioramenti","Controlli superati","Non confermabile","Non applicabile"],labels:{fail:"Errore",warning:"Avviso",pass:"Superato",unable_to_confirm:"Non confermabile",not_applicable:"N/D"}},
 es:{back:"Volver a la auditoría",save:"Guardar como PDF",title:"Informe completo del análisis",subtitle:"Informe SEO, GEO y sectorial basado en evidencias",website:"Web",scanned:"Analizado",loading:"Cargando informe…",failed:"No se pudo cargar el informe.",groups:["Mejoras","Controles superados","No se puede confirmar","No aplicable"],labels:{fail:"Error",warning:"Advertencia",pass:"Superado",unable_to_confirm:"No se puede confirmar",not_applicable:"N/A"}}
};
const esc=(v:unknown)=>String(v??"");
const assessedCounts=(r:any)=>{
  const all=[...(r?.seo?.checks||[]),...(r?.geo?.checks||[])];
  const applicable=all.filter((c:any)=>c.status!=="not_applicable");
  const assessed=applicable.filter((c:any)=>c.status!=="unable_to_confirm");
  return {assessed:assessed.length,applicable:applicable.length,unconfirmed:applicable.length-assessed.length};
};
const reliabilityOf=(r:any)=>{
  const c=assessedCounts(r);
  const scoreCov=c.applicable?c.assessed/c.applicable:0;
  const pages=Number(r?.multiPage?.counts?.audited||1);
  const jsLimited=r?.rendering?.mode==="raw_html"&&!r?.rendering?.javascriptExecuted;
  if(scoreCov>=.9&&pages>=3&&!jsLimited)return "high";
  if(scoreCov>=.7&&pages>=2)return "medium";
  return "limited";
};
const reasonFor=(c:Check,language:Locale)=>{
  const code=(c as any).reasonCode;
  const msg=String(c.message||"").toLowerCase();
  const js=code==="needs_js"||/javascript|client-side|render/.test(msg);
  const weak=code==="weak_evidence"||/onvoldoende|insufficient|niet.*bevestig|unable/.test(msg);
  if(language!=="nl") return c.message||"Evidence was insufficient for a definitive result.";
  if(js)return "Mogelijk pas zichtbaar na JavaScript. RankFix voert niet altijd JavaScript uit.";
  if(code==="cap_absent"||c.status==="not_applicable")return "Deze controle geldt niet voor dit type website.";
  if(code==="insufficient_pages")return "We analyseerden geen representatieve pagina waarop dit betrouwbaar zichtbaar was.";
  if(code==="type_uncertain")return "Het type bedrijf is niet zeker genoeg om te bepalen of deze controle geldt.";
  if(weak)return "We vonden aanwijzingen, maar niet sterk genoeg om dit betrouwbaar te bevestigen.";
  return c.message||"RankFix heeft onvoldoende bewijs om dit betrouwbaar te bevestigen.";
};
const MODULE_LABELS:Record<Locale,Record<string,string>>={
 nl:{core_seo:"SEO",geo:"GEO / AI-zichtbaarheid",technical:"Techniek",security:"Beveiligingsinstellingen",ecommerce:"Webshop",product:"Producten",pricing_currency:"Prijs & valuta",merchant:"Merchant",checkout:"Checkout",eu_consumer:"EU consumenteninfo",local_seo:"Lokale SEO",structured_data:"Gestructureerde data",links:"Links & redirects",accessibility:"Toegankelijkheid",lead_conversion:"Conversie & contact",saas_b2b:"SaaS / B2B",tourism_recreation:"Toerisme & recreatie",service_marketplace:"Dienstenplatform",home_services:"Bouw & installatie",professional_services:"Zakelijke dienstverlening",automotive:"Automotive",health_wellness:"Zorg & gezondheid",hospitality:"Horeca",accommodation:"Verblijf & accommodatie",news_media:"Nieuws & media",business_identity:"Bedrijfsidentiteit",quality_trust:"Kwaliteit & vertrouwen",transport_travel:"Transport & mobiliteit",transport_logistics:"Transport & logistiek",real_estate:"Vastgoed"},
 en:{core_seo:"SEO",geo:"GEO / AI visibility",technical:"Technical",security:"Security settings",ecommerce:"Online store",product:"Products",pricing_currency:"Pricing & currency",merchant:"Merchant",checkout:"Checkout",eu_consumer:"EU consumer information",local_seo:"Local SEO",structured_data:"Structured data",links:"Links & redirects",accessibility:"Accessibility",lead_conversion:"Conversion & contact",saas_b2b:"SaaS / B2B",tourism_recreation:"Tourism & recreation",service_marketplace:"Service marketplace",home_services:"Home services",professional_services:"Professional services",automotive:"Automotive",health_wellness:"Healthcare",hospitality:"Hospitality",accommodation:"Accommodation",news_media:"News & media",business_identity:"Business identity",quality_trust:"Quality & trust",transport_travel:"Transport & mobility",transport_logistics:"Transport & logistics",real_estate:"Real estate"},
 de:{core_seo:"SEO",geo:"GEO / KI-Sichtbarkeit",technical:"Technik",security:"Sicherheitseinstellungen",ecommerce:"Onlineshop",product:"Produkte",pricing_currency:"Preis & Währung",merchant:"Merchant",checkout:"Checkout",eu_consumer:"EU-Verbraucherinformationen",local_seo:"Lokale SEO",structured_data:"Strukturierte Daten",links:"Links & Weiterleitungen",accessibility:"Barrierefreiheit",lead_conversion:"Conversion & Kontakt",saas_b2b:"SaaS / B2B",tourism_recreation:"Tourismus & Freizeit",service_marketplace:"Dienstleistungsplattform",home_services:"Haus & Installation",professional_services:"Unternehmensdienstleistungen",automotive:"Automotive",health_wellness:"Gesundheit & Pflege",hospitality:"Gastronomie",accommodation:"Unterkunft",news_media:"Nachrichten & Medien",business_identity:"Unternehmensidentität",quality_trust:"Qualität & Vertrauen",transport_travel:"Transport & Mobilität",transport_logistics:"Transport & Logistik",real_estate:"Immobilien"},
 fr:{core_seo:"SEO",geo:"GEO / visibilité IA",technical:"Technique",security:"Paramètres de sécurité",ecommerce:"Boutique en ligne",product:"Produits",pricing_currency:"Prix & devise",merchant:"Merchant",checkout:"Paiement",eu_consumer:"Informations consommateurs UE",local_seo:"SEO local",structured_data:"Données structurées",links:"Liens & redirections",accessibility:"Accessibilité",lead_conversion:"Conversion & contact",saas_b2b:"SaaS / B2B",tourism_recreation:"Tourisme & loisirs",service_marketplace:"Plateforme de services",home_services:"Habitat & installation",professional_services:"Services professionnels",automotive:"Automobile",health_wellness:"Santé et soins",hospitality:"Restauration",accommodation:"Hébergement",news_media:"Actualités & médias",business_identity:"Identité de l'entreprise",quality_trust:"Qualité et confiance",transport_travel:"Transport & mobilité",transport_logistics:"Transport et logistique",real_estate:"Immobilier"},
 it:{core_seo:"SEO",geo:"GEO / visibilità IA",technical:"Tecnica",security:"Impostazioni di sicurezza",ecommerce:"Negozio online",product:"Prodotti",pricing_currency:"Prezzi & valuta",merchant:"Merchant",checkout:"Checkout",eu_consumer:"Informazioni consumatori UE",local_seo:"SEO locale",structured_data:"Dati strutturati",links:"Link & reindirizzamenti",accessibility:"Accessibilità",lead_conversion:"Conversione & contatto",saas_b2b:"SaaS / B2B",tourism_recreation:"Turismo & tempo libero",service_marketplace:"Piattaforma di servizi",home_services:"Casa & installazione",professional_services:"Servizi professionali",automotive:"Automotive",health_wellness:"Salute e assistenza",hospitality:"Ristorazione",accommodation:"Alloggio",news_media:"Notizie & media",business_identity:"Identità aziendale",quality_trust:"Qualità e affidabilità",transport_travel:"Trasporti & mobilità",transport_logistics:"Trasporti e logistica",real_estate:"Immobiliare"},
 es:{core_seo:"SEO",geo:"GEO / visibilidad IA",technical:"Técnica",security:"Ajustes de seguridad",ecommerce:"Tienda online",product:"Productos",pricing_currency:"Precio & moneda",merchant:"Merchant",checkout:"Checkout",eu_consumer:"Información al consumidor UE",local_seo:"SEO local",structured_data:"Datos estructurados",links:"Enlaces & redirecciones",accessibility:"Accesibilidad",lead_conversion:"Conversión & contacto",saas_b2b:"SaaS / B2B",tourism_recreation:"Turismo & ocio",service_marketplace:"Plataforma de servicios",home_services:"Hogar & instalación",professional_services:"Servicios profesionales",automotive:"Automoción",health_wellness:"Salud y cuidados",hospitality:"Hostelería",accommodation:"Alojamiento",news_media:"Noticias & medios",business_identity:"Identidad de la empresa",quality_trust:"Calidad y confianza",transport_travel:"Transporte & movilidad",transport_logistics:"Transporte y logística",real_estate:"Inmobiliaria"}
};
const moduleLabel=(v:string,language:Locale)=>MODULE_LABELS[language]?.[v]||MODULE_LABELS.en[v]||v.replaceAll("_"," ");
const AUDIT_UX:Record<Locale,{mainProblems:string;workingWell:string;actions:string;perPage:string;method:string;experts:string;statusGuide:string;proven:string;optimization:string;sample:string;notFull:string;unable:string;na:string}>={
 nl:{mainProblems:"Belangrijkste bewezen problemen",workingWell:"Dit gaat goed",actions:"Aanbevolen acties",perPage:"Per pagina",method:"Methode en dekking",experts:"Voor experts",statusGuide:"Statusuitleg",proven:"Bewezen fout",optimization:"Optimalisatie",sample:"representatieve selectie",notFull:"Dit is een steekproef, geen volledige scan van elke pagina.",unable:"Niet te bevestigen: onvoldoende bewijs",na:"N.v.t.: geldt niet voor deze website"},
 en:{mainProblems:"Main proven problems",workingWell:"What is working well",actions:"Recommended actions",perPage:"Per page",method:"Method and coverage",experts:"For experts",statusGuide:"Status guide",proven:"Proven issue",optimization:"Optimization",sample:"representative selection",notFull:"This is a representative sample, not a complete scan of every page.",unable:"Unable to confirm: insufficient evidence",na:"N/A: does not apply"},
 de:{mainProblems:"Wichtigste nachgewiesene Probleme",workingWell:"Das funktioniert gut",actions:"Empfohlene Maßnahmen",perPage:"Pro Seite",method:"Methode und Abdeckung",experts:"Für Experten",statusGuide:"Statuslegende",proven:"Nachgewiesenes Problem",optimization:"Optimierung",sample:"repräsentative Auswahl",notFull:"Dies ist eine repräsentative Stichprobe, kein vollständiger Scan jeder Seite.",unable:"Nicht bestätigbar: unzureichende Nachweise",na:"Nicht zutreffend: gilt nicht für diese Website"},
 fr:{mainProblems:"Principaux problèmes prouvés",workingWell:"Ce qui fonctionne bien",actions:"Actions recommandées",perPage:"Par page",method:"Méthode et couverture",experts:"Pour les experts",statusGuide:"Guide des statuts",proven:"Problème prouvé",optimization:"Optimisation",sample:"sélection représentative",notFull:"Il s’agit d’un échantillon représentatif, pas d’une analyse complète de chaque page.",unable:"Impossible à confirmer : preuves insuffisantes",na:"Non applicable : ne s’applique pas à ce site"},
 it:{mainProblems:"Principali problemi dimostrati",workingWell:"Cosa funziona bene",actions:"Azioni consigliate",perPage:"Per pagina",method:"Metodo e copertura",experts:"Per esperti",statusGuide:"Guida agli stati",proven:"Problema dimostrato",optimization:"Ottimizzazione",sample:"selezione rappresentativa",notFull:"È un campione rappresentativo, non una scansione completa di ogni pagina.",unable:"Non confermabile: prove insufficienti",na:"Non applicabile: non vale per questo sito"},
 es:{mainProblems:"Principales problemas demostrados",workingWell:"Lo que funciona bien",actions:"Acciones recomendadas",perPage:"Por página",method:"Método y cobertura",experts:"Para expertos",statusGuide:"Guía de estados",proven:"Problema demostrado",optimization:"Optimización",sample:"selección representativa",notFull:"Es una muestra representativa, no un análisis completo de cada página.",unable:"No se puede confirmar: evidencia insuficiente",na:"No aplicable: no corresponde a este sitio"}
};

export default function FullAuditReport(){
  const {id}=useParams<{id:string}>();
  const [scan,setScan]=useState<Scan|null>(null);
  const [error,setError]=useState("");
  const [language,setLanguage]=useState<Locale>("nl");
  const t=reportText[language];
  const ux=AUDIT_UX[language];
  const auditedUrl=scan?.final_url||scan?.result?.finalUrl||scan?.scanned_url||"";
  const inputDiffers=Boolean(scan?.scanned_url&&auditedUrl&&scan.scanned_url!==auditedUrl);
 const deep=language==="nl"?{basis:"Scanbasis & websiteprofiel",next:"Volgende stap",rule:"Regel",category:"categorie",confidence:"zekerheid",evidence:"Bewijs",commerce:"Product & webshopdiagnostiek",technical:"Technische scaninformatie",page:"Pagina",reportId:"Rapport-ID",pageProof:"Paginatype bewijs",noData:"Geen gegevens beschikbaar."}:
 language==="de"?{basis:"Scanbasis & Websiteprofil",next:"Nächster Schritt",rule:"Regel",category:"Kategorie",confidence:"Sicherheit",evidence:"Nachweis",commerce:"Produkt- & Shopdiagnostik",technical:"Technische Scaninformationen",page:"Seite",reportId:"Bericht-ID",pageProof:"Seitentyp-Nachweis",noData:"Keine Daten verfügbar."}:
 language==="fr"?{basis:"Base d’analyse & profil du site",next:"Étape suivante",rule:"Règle",category:"catégorie",confidence:"confiance",evidence:"Preuve",commerce:"Diagnostic produit & boutique",technical:"Informations techniques de l’analyse",page:"Page",reportId:"ID du rapport",pageProof:"Preuve du type de page",noData:"Aucune donnée disponible."}:
 language==="it"?{basis:"Base scansione & profilo sito",next:"Passaggio successivo",rule:"Regola",category:"categoria",confidence:"affidabilità",evidence:"Prova",commerce:"Diagnostica prodotto & negozio",technical:"Informazioni tecniche scansione",page:"Pagina",reportId:"ID report",pageProof:"Prova tipo pagina",noData:"Nessun dato disponibile."}:
 language==="es"?{basis:"Base del análisis & perfil web",next:"Siguiente paso",rule:"Regla",category:"categoría",confidence:"confianza",evidence:"Evidencia",commerce:"Diagnóstico de producto & tienda",technical:"Información técnica del análisis",page:"Página",reportId:"ID del informe",pageProof:"Evidencia del tipo de página",noData:"No hay datos disponibles."}:
 {basis:"Scan basis & website profile",next:"Next step",rule:"Rule",category:"category",confidence:"confidence",evidence:"Evidence",commerce:"Product & store diagnostics",technical:"Technical scan information",page:"Page",reportId:"Report ID",pageProof:"Page-type evidence",noData:"No data available."};

  useEffect(()=>{fetch("/api/account/language").then(r=>r.ok?r.json():null).then(d=>{if(d?.language&&d.language in reportText)setLanguage(d.language)}).catch(()=>{});if(!id)return;fetch("/api/history/"+encodeURIComponent(id),{cache:"no-store"}).then(async r=>{const d=await r.json();if(r.status===401){location.href="/account";return;}if(!r.ok)throw new Error(d.error||t.failed);setScan({...d.scan,id});}).catch(e=>setError(e instanceof Error?e.message:t.failed));},[id]);
  const checks=useMemo(()=>{
    const raw:Check[]=[...(scan?.result?.seo?.checks||[]),...(scan?.result?.geo?.checks||[])];
    const rank:Record<string,number>={fail:5,warning:4,pass:3,unable_to_confirm:2,not_applicable:1};
    const map=new Map<string,Check>();
    raw.forEach(c=>{const k=[String(c.category||"").toLowerCase(),String(c.rule_id||c.issue_id||c.title).toLowerCase()].join(":");const old=map.get(k);if(!old||(rank[c.status]||0)>(rank[old.status]||0))map.set(k,c);});
    return [...map.values()];
  },[scan]);
  const groups=[
    [t.groups[0],checks.filter(c=>c.status==="fail"||c.status==="warning")],
    [t.groups[1],checks.filter(c=>c.status==="pass")],
    [t.groups[2],checks.filter(c=>c.status==="unable_to_confirm")],
    [t.groups[3],checks.filter(c=>c.status==="not_applicable")],
  ] as const;
  if(error)return <main className="report-wrap"><p>{error}</p></main>;
  if(!scan)return <main className="report-wrap"><p>{t.loading}</p></main>;
  const r=scan.result||{}; const profile=r.technologyProfile; const sector=r.sectorProfile; const rendering=r.rendering; const pageType=r.pageTypeEvidence;
  const visibleSectorEvidence=(sector?.evidence||[]).filter((value:string)=>!/^Vorige voorlopige sector:/i.test(String(value)));
  const sitewideWarnings=(r.multiPage?.sitewideCheckAggregation||[]).filter((item:any)=>item.status==="WARNING");
  const sitewideWarningKeys=new Set(sitewideWarnings.map((item:any)=>String(item.key||"")));
  const warningCount=checks.filter(c=>c.status==="warning").length;
  const groupByReason=(items:Check[])=>Array.from(items.reduce((map,check)=>{const reason=reasonFor(check,language);const key=reason.toLowerCase();const current=map.get(key);if(current)current.items.push(check);else map.set(key,{reason,items:[check]});return map;},new Map<string,{reason:string;items:Check[]}>()).values());
  const groupedUnable=groupByReason(checks.filter(c=>c.status==="unable_to_confirm"));
  const groupedNa=groupByReason(checks.filter(c=>c.status==="not_applicable"));
  return <main className="report-wrap">
    <div className="report-actions"><Link href={"/dashboard/audit/"+encodeURIComponent(id)} className="report-button">← {t.back}</Link><button className="report-button primary" onClick={()=>window.print()}>{language==="nl"?"PDF downloaden":t.save}</button></div>
    <header className="report-header"><div><div className="report-brand">RankFix <span>AI</span></div><h1>{t.title}</h1><p className="muted">{t.subtitle}</p></div><div className="score"><b>{r.overallScore??"—"}</b><span>/ 100</span></div></header>
    <div className="box score-explainer"><b>{language==="nl"?"Wat betekent deze score?":"What does this score mean?"}</b><p>{language==="nl"?"De score geldt voor de controles die RankFix tijdens deze scan betrouwbaar kon beoordelen. 100/100 betekent niet dat een website op ieder gebied perfect is, gegarandeerd hoog rankt of door AI-zoekmachines wordt genoemd. Niet te bevestigen en N.v.t. worden apart getoond en verlagen de score niet.":"The score applies to checks RankFix could reliably assess during this scan. 100/100 does not mean a website is perfect in every area, guaranteed to rank highly, or guaranteed to be cited by AI search. Unable-to-confirm and N/A checks are shown separately and do not lower the score."}</p><p><b>{language==="nl"?"Berekening:":"Calculation:"}</b> {r.scoreModel?.formula||"0.6 × SEO + 0.4 × GEO"} · Security {language==="nl"?"staat apart en telt niet mee in het totaal.":"is separate and is not included in the total."}</p>{(()=>{const c=assessedCounts(r);const rel=reliabilityOf(r);const pages=Number(r.multiPage?.counts?.audited||1);const relLabel=language==="nl"?(rel==="high"?"Hoog":rel==="medium"?"Gemiddeld":"Beperkt"):(rel==="high"?"High":rel==="medium"?"Medium":"Limited");return <><p><b>{language==="nl"?"Betrouwbaarheid:":"Reliability:"}</b> {relLabel}. {language==="nl"?`We beoordeelden ${c.assessed} van de ${c.applicable} toepasselijke controles op ${pages} pagina's van de website.`:`We assessed ${c.assessed} of ${c.applicable} applicable checks across ${pages} website pages.`}</p><p><b>{language==="nl"?"Geanalyseerde pagina's:":"Analysed pages:"}</b> {pages} ({ux.sample}). {ux.notFull}</p>{c.unconfirmed>0&&<p>{language==="nl"?`${c.unconfirmed} controles konden niet worden bevestigd; de score kan hierdoor afwijken.`:`${c.unconfirmed} checks could not be confirmed; this may affect the score.`}</p>}</>})()}</div><section className="summary-grid"><div><span>{t.website}</span><strong>{auditedUrl}</strong>{inputDiffers&&<small style={{display:"block",marginTop:4,opacity:.7}}>{language==="nl"?"Ingevoerde URL":"Input URL"}: {scan.scanned_url}</small>}</div><div><span>{t.scanned}</span><strong>{new Date(scan.created_at).toLocaleString(language,{dateStyle:"long",timeStyle:"short"})}</strong></div><div><span>SEO</span><strong>{r.seo?.score??"—"} / 100</strong></div><div><span>GEO</span><strong>{r.geo?.score??"—"} / 100</strong></div><div><span>{language==="nl"?"Beveiligingsinstellingen":"Security settings"}</span><strong>{r.security?.score??"—"} / 100</strong><small style={{display:"block",marginTop:4,opacity:.7}}>{language==="nl"?"Passieve controle · telt niet mee in totaalscore":"Passive check · excluded from total score"}</small></div><div><span>{language==="nl"?"Toegankelijkheid (basis)":"Accessibility (basic)"}</span><strong>{(r.accessibility?.coverage?.assessedWeight??0)>0?(r.accessibility?.score??"—")+" / 100":(language==="nl"?"Niet te bevestigen":"Unable to confirm")}</strong></div></section>
    <section><h2>{deep.basis}</h2><div className="box"><p><b>Scanbewijs:</b> {rendering?.mode==="raw_html"?"Raw HTML":"Rendered"} · JavaScript {rendering?.javascriptExecuted?"uitgevoerd":"niet uitgevoerd"}{pageType?.type?" · paginatype "+pageType.type+" ("+pageType.confidence+")":""}</p>{rendering?.note&&<p>{rendering.note}</p>}<p><b>Websiteprofiel:</b> {sector?.key==="saas_b2b"?"SaaS / webapp":profile?.siteType||"Website"} · CMS: {profile?.cms||"Niet bevestigd"} · Platform: {profile?.commercePlatform||"Niet bevestigd"} · Framework: {profile?.framework||"Niet bevestigd"} · zekerheid {profile?.confidence??"—"}%</p>{profile?.evidence?.length>0&&<p><b>Websitebewijs:</b> {profile.evidence.slice(0,3).join(" · ")}</p>}{sector&&<><p><b>Sector:</b> {sector.label||"Sector niet bevestigd"} · zekerheid {sector.confidenceScore??"—"}%</p>{visibleSectorEvidence.length>0&&<p><b>Beslissend sectorbewijs:</b> {visibleSectorEvidence.slice(-3).join(" · ")}</p>}{sector.applicableModules?.length>0&&<p><b>Actieve scanmodules:</b> {sector.applicableModules.map((m:string)=>moduleLabel(m,language)).join(" · ")}</p>}</>}</div></section>
    <section><h2>{ux.mainProblems}</h2><div className="box">{checks.filter(c=>c.status==="fail"&&Boolean(c.evidence?.details)).sort((a,b)=>(b.maxPoints??0)-(a.maxPoints??0)).slice(0,3).map((c,i)=><div className="diagnostic-block" key={(c.rule_id||c.title)+i}><p><span className="status fail">{language==="nl"?"Probleem":"Problem"}</span> <b>{c.title}</b></p><p>{c.message}</p>{c.fix&&<p><b>{language==="nl"?"Wat u kunt doen":"What you can do"}:</b> {c.fix}</p>}</div>)}{checks.filter(c=>c.status==="fail"&&Boolean(c.evidence?.details)).length===0&&<p>{language==="nl"?(warningCount?`Geen kritieke problemen gevonden. Wel ${warningCount} optimalisatiepunt${warningCount===1?"":"en"}.`:"Geen kritieke problemen gevonden."):(warningCount?`No critical problems found. There are ${warningCount} optimization point${warningCount===1?"":"s"}.`:"No critical problems found.")}</p>}</div></section>
    <section><h2>{ux.workingWell}</h2><div className="box">{checks.filter(c=>c.status==="pass"&&Boolean(c.evidence?.details)&&!sitewideWarningKeys.has(String(c.key||""))).sort((a,b)=>(b.maxPoints??0)-(a.maxPoints??0)).slice(0,3).map((c,i)=><p key={(c.rule_id||c.title)+i}>✓ <b>{c.title}</b> · {c.message}</p>)}</div></section>
    <section><h2>{ux.actions}</h2><div className="box">{checks.filter(c=>(c.status==="fail"||c.status==="warning")&&Boolean(c.fix)).sort((a,b)=>a.status===b.status?(b.maxPoints??0)-(a.maxPoints??0):a.status==="fail"?-1:1).slice(0,5).map((c,i)=><div className="diagnostic-block" key={(c.rule_id||c.title)+i}><p><b>{i+1}. {c.title}</b> · {c.status==="fail"?(language==="nl"?"Bewezen fout":"Proven issue"):(language==="nl"?"Optimalisatie":"Optimization")}</p><p>{c.fix}</p></div>)}</div></section>
    {r.multiPage?.enabled&&<section><h2>{ux.perPage}</h2><div className="box"><p><b>{language==="nl"?"Gemiddelde paginascore:":"Average page score:"}</b> {r.multiPage.siteSampleScore==null?"—":r.multiPage.siteSampleScore+" / 100"} · {language==="nl"?"gecontroleerd":"analysed"} {r.multiPage.counts?.audited??0} · {language==="nl"?"niet te bevestigen":"unable to confirm"} {r.multiPage.counts?.unableToConfirm??0}.</p>{(r.multiPage.pageAudits?.length?r.multiPage.pageAudits:r.multiPage.selectedPages||[]).map((p:any,i:number)=><div className="diagnostic-block" key={i}><h3>{esc(p.type)} {p.score!=null?"· "+p.score+" / 100":""}</h3>{p.title&&<p><b>Titel:</b> {esc(p.title)}</p>}<p><b>URL:</b> {esc(p.url)}</p>{p.httpStatus!=null&&<p><b>HTTP:</b> {esc(p.httpStatus)}</p>}{p.status&&<p><b>Status:</b> {p.status==="audited"?"Gecontroleerd":"Niet te bevestigen"}</p>}{p.evidenceChecks?.map((e:any,j:number)=><p key={j}><b>{esc(e.key)}:</b> {esc(e.details)}</p>)}</div>)}</div></section>}
    {sitewideWarnings.length>0&&<section><h2>{language==="nl"?"Sitebrede steekproef":"Sitewide sample"}</h2><div className="box"><p>{language==="nl"?"Deze punten zijn bewezen op één of meer representatieve pagina\'s en veranderen de score van de oorspronkelijk gescande pagina niet automatisch.":"These points were proven on one or more representative pages and do not automatically change the score of the originally scanned page."}</p>{sitewideWarnings.map((item:any)=><div className="diagnostic-block" key={item.key}><p><b>{item.key==="title"?"Meta title":item.key==="description"?"Meta description":item.key==="h1"?"H1-heading":item.key==="canonical"?"Canonical URL":item.key}</b> · {item.affectedUrls?.length||0} {language==="nl"?"representatieve URL(s) vragen aandacht":"representative URL(s) need attention"}</p>{item.affectedUrls?.length>0&&<p>{item.affectedUrls.join(" · ")}</p>}</div>)}</div></section>}
    {groups.map(([title,list],groupIndex)=><section key={title}><h2>{title} <small>({list.length})</small></h2>{list.length===0?<p className="empty">Geen items.</p>:groupIndex===3?<div className="box">{groupedNa.map((group,i)=><div key={i} className="diagnostic-block"><p><span className="status not_applicable">— {group.items.length} {language==="nl"?"controles overgeslagen":"checks skipped"}</span></p><p>{group.reason}</p><p className="meta">{group.items.slice(0,12).map(item=>item.title).join(" · ")}{group.items.length>12?` · +${group.items.length-12}`:""}</p></div>)}</div>:groupIndex===1?<div className="box"><div className="flex flex-wrap gap-2">{list.filter(c=>!sitewideWarningKeys.has(String(c.key||""))).map((c,i)=><span key={(c.rule_id||c.title)+i} className="status pass">✓ {c.title}</span>)}</div></div>:groupIndex===2?<div className="box">{groupedUnable.map((group,i)=><details key={i} className="diagnostic-block"><summary><b>? {group.items.length===1?group.items[0].title:`${group.items.length} controles met dezelfde reden`}</b></summary><p>{group.reason}</p>{group.items.length>1&&<p className="meta">{group.items.slice(0,10).map(item=>item.title).join(" · ")}</p>}</details>)}</div>:list.map((c,i)=><article className="finding" key={(c.rule_id||c.title)+i}><div className="finding-head"><h3>{c.title}</h3><span className={"status "+c.status}>{t.labels[c.status]||c.status}</span></div><p>{c.message}</p>{c.fix&&<p><b>{deep.next}:</b> {c.fix}</p>}{c.evidence?.details&&c.evidence.details!==c.message&&<p className="evidence"><b>{deep.evidence}:</b> {c.evidence.details}</p>}</article>)}</section>)}
    {r.security?.checks?.length>0&&<section><h2>{language==="nl"?"Beveiligingsinstellingen (passieve controle)":"Security settings (passive check)"}</h2><div className="box"><p>{language==="nl"?"RankFix test niet actief op kwetsbaarheden. We controleren alleen wat openbaar zichtbaar is, zoals headers en cookie-instellingen.":"RankFix does not actively test for vulnerabilities. It only checks publicly visible settings such as headers and cookie attributes."}</p><p><b>{language==="nl"?"Score beveiligingsinstellingen:":"Security settings score:"}</b> {r.security.score??"—"} / 100 · {r.security.note||""}</p>{r.security.checks.map((c:Check,i:number)=><div className="diagnostic-block" key={(c.rule_id||c.title)+i}><p><b>{c.status==="pass"?"✓":c.status==="not_applicable"?"—":c.status==="unable_to_confirm"?"?":"!"} {c.title}</b> · {t.labels[c.status]||c.status}{c.maxPoints!==undefined?" · "+(c.points??0)+"/"+c.maxPoints:""}</p><p>{c.message}</p></div>)}</div></section>}
    {(sector?.sector==="ecommerce"||sector?.key==="ecommerce"||profile?.isCommerce)&&<section><h2>{deep.commerce}</h2><div className="box">
      {[
        ["Product Optimizer",r.metrics?.productOptimizer],
        ["Prijs & valuta",r.metrics?.pricingCurrency],
        ["EU-Omnibus & Consumer Rights",r.metrics?.euConsumerSignals],
        ["Checkout & funnel",r.metrics?.checkoutFunnel]
      ].map(([title,data]:any)=><div key={title} className="diagnostic-block"><h3>{title}</h3>{data&&typeof data==="object"?Object.entries(data).map(([key,value])=><p key={key}><b>{key}:</b> {Array.isArray(value)?(value.length?value.map(v=>typeof v==="object"?JSON.stringify(v):String(v)).join(" · "):"—"):value&&typeof value==="object"?JSON.stringify(value):value===true?"Ja":value===false?"Nee":value==null?"—":String(value)}</p>):<p>{deep.noData}</p>}</div>)}
    </div></section>}
    <section><h2>{ux.method}</h2><div className="box"><p>{language==="nl"?"RankFix analyseert een representatieve selectie van pagina's. Dit is geen volledige scan van iedere pagina. Niet te bevestigen betekent onvoldoende bewijs; N.v.t. betekent dat de controle niet voor deze website geldt.":"RankFix analyses a representative selection of pages. This is not a complete scan of every page. Unable to confirm means insufficient evidence; N/A means the check does not apply."}</p></div></section><section><details><summary><h2 style={{display:"inline"}}>{ux.experts}</h2></summary><div className="box"><p><b>{language==="nl"?"Alternatieve/ruwe sectorbewijzen":"Raw sector evidence"}:</b> {visibleSectorEvidence.join(" · ")||"—"}</p><p><b>{language==="nl"?"Actieve capabilities/modules":"Active capabilities/modules"}:</b> {(sector?.applicableModules||[]).map((m:string)=>moduleLabel(m,language)).join(" · ")||"—"}</p></div></details></section><section><h2>{deep.technical}</h2><div className="box"><p><b>{deep.page}:</b> {auditedUrl}</p>{inputDiffers&&<p><b>{language==="nl"?"Ingevoerde URL":"Input URL"}:</b> {scan.scanned_url}</p>}<p><b>{deep.reportId}:</b> {scan.id||id}</p><p><b>Rendering:</b> {rendering?.mode||"—"} · JavaScript: {String(rendering?.javascriptExecuted??false)}</p><p><b>{deep.pageProof}:</b> {(pageType?.evidence||[]).join(" · ")||"Niet beschikbaar"}</p><p><b>Scoremodel:</b> {r.scoreModel?.version||"legacy"} · {r.scoreModel?.formula||"0.6 × SEO + 0.4 × GEO"} · coverage {r.coverage?.coveragePercent??"—"}%</p></div></section>
    <div className="box"><p><b>{ux.statusGuide}</b></p><p>✓ {language==="nl"?"Goed: aangetoond in orde":"Good: proven OK"} · ! {language==="nl"?"Aandachtspunt: optimalisatie":"Attention: optimization"} · ! {language==="nl"?"Probleem: aantoonbaar probleem":"Problem: proven issue"} · ? {ux.unable} · — {ux.na}</p></div>
    <footer>RankFix AI · Dit rapport beschrijft wat tijdens deze scan aantoonbaar was. Niet te bevestigen en N.v.t. verlagen de score niet. EU/Omnibus-signalen zijn geen juridische conformiteitsverklaring.</footer>
  </main>;
}
