"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import type { Locale } from "@/lib/locales";
import "./report.css";

type Check={key?:string;category?:string;title:string;status:string;severity?:string;message:string;fix?:string;rule_id?:string;issue_id?:string;confidence?:string;evidence?:{details?:string;found?:unknown};points?:number;maxPoints?:number};
type Scan={id?:string;scanned_url:string;created_at:string;result:any};

const reportText:Record<Locale,{back:string;save:string;title:string;subtitle:string;website:string;scanned:string;loading:string;failed:string;groups:string[];labels:Record<string,string>}>={
 nl:{back:"Terug naar audit",save:"Opslaan als PDF",title:"Volledig scanrapport",subtitle:"Bewijsgericht SEO-, GEO- en sectorrapport",website:"Website",scanned:"Gescand",loading:"Rapport laden…",failed:"Rapport kon niet worden geladen.",groups:["Verbeterpunten","Geslaagde controles","Niet te bevestigen","Niet van toepassing"],labels:{fail:"Fout",warning:"Waarschuwing",pass:"Geslaagd",unable_to_confirm:"Niet te bevestigen",not_applicable:"N.v.t."}},
 en:{back:"Back to audit",save:"Save as PDF",title:"Full scan report",subtitle:"Evidence-based SEO, GEO and sector report",website:"Website",scanned:"Scanned",loading:"Loading report…",failed:"Could not load report.",groups:["Improvements","Passed checks","Unable to confirm","Not applicable"],labels:{fail:"Error",warning:"Warning",pass:"Passed",unable_to_confirm:"Unable to confirm",not_applicable:"N/A"}},
 de:{back:"Zurück zum Audit",save:"Als PDF speichern",title:"Vollständiger Scanbericht",subtitle:"Evidenzbasierter SEO-, GEO- und Branchenbericht",website:"Website",scanned:"Gescannt",loading:"Bericht wird geladen…",failed:"Bericht konnte nicht geladen werden.",groups:["Verbesserungen","Bestandene Prüfungen","Nicht bestätigbar","Nicht zutreffend"],labels:{fail:"Fehler",warning:"Warnung",pass:"Bestanden",unable_to_confirm:"Nicht bestätigbar",not_applicable:"N. z."}},
 fr:{back:"Retour à l’audit",save:"Enregistrer en PDF",title:"Rapport d’analyse complet",subtitle:"Rapport SEO, GEO et sectoriel fondé sur des preuves",website:"Site",scanned:"Analysé",loading:"Chargement du rapport…",failed:"Impossible de charger le rapport.",groups:["Améliorations","Contrôles réussis","Impossible à confirmer","Non applicable"],labels:{fail:"Erreur",warning:"Avertissement",pass:"Réussi",unable_to_confirm:"Impossible à confirmer",not_applicable:"N/A"}},
 it:{back:"Torna all’audit",save:"Salva come PDF",title:"Report completo della scansione",subtitle:"Report SEO, GEO e di settore basato su evidenze",website:"Sito",scanned:"Scansionato",loading:"Caricamento report…",failed:"Impossibile caricare il report.",groups:["Miglioramenti","Controlli superati","Non confermabile","Non applicabile"],labels:{fail:"Errore",warning:"Avviso",pass:"Superato",unable_to_confirm:"Non confermabile",not_applicable:"N/D"}},
 es:{back:"Volver a la auditoría",save:"Guardar como PDF",title:"Informe completo del análisis",subtitle:"Informe SEO, GEO y sectorial basado en evidencias",website:"Web",scanned:"Analizado",loading:"Cargando informe…",failed:"No se pudo cargar el informe.",groups:["Mejoras","Controles superados","No se puede confirmar","No aplicable"],labels:{fail:"Error",warning:"Advertencia",pass:"Superado",unable_to_confirm:"No se puede confirmar",not_applicable:"N/A"}}
};
const esc=(v:unknown)=>String(v??"");
const moduleLabel=(v:string)=>({core_seo:"SEO",geo:"GEO / AI-zichtbaarheid",technical:"Techniek",security:"Security",ecommerce:"Webshop",product:"Producten",pricing_currency:"Prijs & valuta",merchant:"Merchant",checkout:"Checkout",eu_consumer:"EU consumenteninfo",local_seo:"Local SEO",structured_data:"Structured Data",links:"Links & redirects",accessibility:"Toegankelijkheid",lead_conversion:"Conversie & contact",saas_b2b:"SaaS / B2B",financial_services:"Financiële dienstverlening",tourism_recreation:"Toerisme & recreatie",service_marketplace:"Dienstenplatform",home_services:"Bouw & installatie",professional_services:"Zakelijke dienstverlening",automotive:"Automotive",health_wellness:"Zorg & gezondheid",hospitality:"Horeca",news_media:"Nieuws & media"} as Record<string,string>)[v]||v.replaceAll("_"," ");

export default function FullAuditReport(){
  const {id}=useParams<{id:string}>();
  const [scan,setScan]=useState<Scan|null>(null);
  const [error,setError]=useState("");
  const [language,setLanguage]=useState<Locale>("nl");
  const t=reportText[language];
 const deep=language==="nl"?{basis:"Scanbasis & websiteprofiel",next:"Volgende stap",rule:"Regel",category:"categorie",confidence:"zekerheid",evidence:"Bewijs",commerce:"Product & webshopdiagnostiek",technical:"Technische scaninformatie",page:"Pagina",reportId:"Rapport-ID",pageProof:"Paginatype bewijs",noData:"Geen gegevens beschikbaar."}:
 language==="de"?{basis:"Scanbasis & Websiteprofil",next:"Nächster Schritt",rule:"Regel",category:"Kategorie",confidence:"Sicherheit",evidence:"Nachweis",commerce:"Produkt- & Shopdiagnostik",technical:"Technische Scaninformationen",page:"Seite",reportId:"Bericht-ID",pageProof:"Seitentyp-Nachweis",noData:"Keine Daten verfügbar."}:
 language==="fr"?{basis:"Base d’analyse & profil du site",next:"Étape suivante",rule:"Règle",category:"catégorie",confidence:"confiance",evidence:"Preuve",commerce:"Diagnostic produit & boutique",technical:"Informations techniques de l’analyse",page:"Page",reportId:"ID du rapport",pageProof:"Preuve du type de page",noData:"Aucune donnée disponible."}:
 language==="it"?{basis:"Base scansione & profilo sito",next:"Passaggio successivo",rule:"Regola",category:"categoria",confidence:"affidabilità",evidence:"Prova",commerce:"Diagnostica prodotto & negozio",technical:"Informazioni tecniche scansione",page:"Pagina",reportId:"ID report",pageProof:"Prova tipo pagina",noData:"Nessun dato disponibile."}:
 language==="es"?{basis:"Base del análisis & perfil web",next:"Siguiente paso",rule:"Regla",category:"categoría",confidence:"confianza",evidence:"Evidencia",commerce:"Diagnóstico de producto & tienda",technical:"Información técnica del análisis",page:"Página",reportId:"ID del informe",pageProof:"Evidencia del tipo de página",noData:"No hay datos disponibles."}:
 {basis:"Scan basis & website profile",next:"Next step",rule:"Rule",category:"category",confidence:"confidence",evidence:"Evidence",commerce:"Product & store diagnostics",technical:"Technical scan information",page:"Page",reportId:"Report ID",pageProof:"Page-type evidence",noData:"No data available."};

  useEffect(()=>{fetch("/api/account/language").then(r=>r.ok?r.json():null).then(d=>{if(d?.language&&d.language in reportText)setLanguage(d.language)}).catch(()=>{});if(!id)return;fetch("/api/history/"+encodeURIComponent(id),{cache:"no-store"}).then(async r=>{const d=await r.json();if(r.status===401){location.href="/account";return;}if(!r.ok)throw new Error(d.error||t.failed);setScan({...d.scan,id});}).catch(e=>setError(e instanceof Error?e.message:t.failed));},[id]);
  const checks=useMemo(()=>{
    const raw:Check[]=[...(scan?.result?.seo?.checks||[]),...(scan?.result?.geo?.checks||[])];
    const rank:Record<string,number>={fail:5,warning:4,pass:3,unable_to_confirm:2,not_applicable:1};
    const map=new Map<string,Check>();
    raw.forEach(c=>{const k=[String(c.category||"").toLowerCase(),String(c.rule_id||c.issue_id||c.title).toLowerCase()].join(":");const old=map.get(k);if(!old||(rank[c.status]||0)>(rank[old.status]||0))map.set(k,c);});
    return [...map.values()];
  },[scan]);
  const groups=[
    [t.groups[0],checks.filter(c=>c.status==="fail"||c.status==="warning")],
    [t.groups[1],checks.filter(c=>c.status==="pass")],
    [t.groups[2],checks.filter(c=>c.status==="unable_to_confirm")],
    [t.groups[3],checks.filter(c=>c.status==="not_applicable")],
  ] as const;
  if(error)return <main className="report-wrap"><p>{error}</p></main>;
  if(!scan)return <main className="report-wrap"><p>{t.loading}</p></main>;
  const r=scan.result||{}; const profile=r.technologyProfile; const sector=r.sectorProfile; const rendering=r.rendering; const pageType=r.pageTypeEvidence;
  return <main className="report-wrap">
    <div className="report-actions"><Link href={"/dashboard/audit/"+encodeURIComponent(id)} className="report-button">← {t.back}</Link><button className="report-button primary" onClick={()=>window.print()}>{language==="nl"?"PDF downloaden":t.save}</button></div>
    <header className="report-header"><div><div className="report-brand">RankFix <span>AI</span></div><h1>{t.title}</h1><p className="muted">{t.subtitle}</p></div><div className="score"><b>{r.overallScore??"—"}</b><span>/ 100</span></div></header>
    <div className="box score-explainer"><b>{language==="nl"?"Wat betekent deze score?":"What does this score mean?"}</b><p>{language==="nl"?"De score geldt voor de controles die RankFix tijdens deze scan betrouwbaar kon beoordelen. 100/100 betekent niet dat een website op ieder gebied perfect is, gegarandeerd hoog rankt of door AI-zoekmachines wordt genoemd. Niet te bevestigen en N.v.t. worden apart getoond en verlagen de score niet.":"The score applies to checks RankFix could reliably assess during this scan. 100/100 does not mean a website is perfect in every area, guaranteed to rank highly, or guaranteed to be cited by AI search. Unable-to-confirm and N/A checks are shown separately and do not lower the score."}</p></div><section className="summary-grid"><div><span>{t.website}</span><strong>{scan.scanned_url}</strong></div><div><span>{t.scanned}</span><strong>{new Date(scan.created_at).toLocaleString(language,{dateStyle:"long",timeStyle:"short"})}</strong></div><div><span>SEO</span><strong>{r.seo?.score??"—"} / 100</strong></div><div><span>GEO</span><strong>{r.geo?.score??"—"} / 100</strong></div><div><span>Security</span><strong>{r.security?.score??"—"} / 100</strong></div></section>
    <section><h2>{deep.basis}</h2><div className="box"><p><b>Scanbewijs:</b> {rendering?.mode==="raw_html"?"Raw HTML":"Rendered"} · JavaScript {rendering?.javascriptExecuted?"uitgevoerd":"niet uitgevoerd"}{pageType?.type?" · paginatype "+pageType.type+" ("+pageType.confidence+")":""}</p>{rendering?.note&&<p>{rendering.note}</p>}<p><b>Websiteprofiel:</b> {sector?.key==="saas_b2b"?"SaaS / webapp":profile?.siteType||"Website"} · CMS: {profile?.cms||"Niet bevestigd"} · Platform: {profile?.commercePlatform||"Niet bevestigd"} · Framework: {profile?.framework||"Niet bevestigd"} · zekerheid {profile?.confidence??"—"}%</p>{profile?.evidence?.length>0&&<p><b>Websitebewijs:</b> {profile.evidence.join(" · ")}</p>}{sector&&<><p><b>Sector:</b> {sector.label||"Sector niet bevestigd"} · zekerheid {sector.confidenceScore??"—"}%</p>{sector.evidence?.length>0&&<p><b>Sectorbewijs:</b> {sector.evidence.join(" · ")}</p>}{sector.applicableModules?.length>0&&<p><b>Actieve scanmodules:</b> {sector.applicableModules.map((m:string)=>moduleLabel(m)).join(" · ")}</p>}</>}</div></section>
    {r.multiPage?.enabled&&<section><h2>Multi-page scan</h2><div className="box"><p><b>Site-samplescore:</b> {r.multiPage.siteSampleScore==null?"—":r.multiPage.siteSampleScore+" / 100"} · gecontroleerd {r.multiPage.counts?.audited??0} van {(r.multiPage.counts?.audited??0)+(r.multiPage.counts?.unableToConfirm??0)} ({r.multiPage.coveragePercent??"—"}% dekking) · niet te bevestigen {r.multiPage.counts?.unableToConfirm??0}. Deze score staat los van de huidige paginascore.</p>{(r.multiPage.pageAudits?.length?r.multiPage.pageAudits:r.multiPage.selectedPages||[]).map((p:any,i:number)=><div className="diagnostic-block" key={i}><h3>{esc(p.type)} {p.score!=null?"· "+p.score+" / 100":""}</h3>{p.title&&<p><b>Titel:</b> {esc(p.title)}</p>}<p><b>URL:</b> {esc(p.url)}</p>{p.httpStatus!=null&&<p><b>HTTP:</b> {esc(p.httpStatus)}</p>}{p.status&&<p><b>Status:</b> {p.status==="audited"?"Gecontroleerd":"Niet te bevestigen"}</p>}{p.evidenceChecks?.map((e:any,j:number)=><p key={j}><b>{esc(e.key)}:</b> {esc(e.details)}</p>)}</div>)}</div></section>}
    {groups.map(([title,list],groupIndex)=><section key={title}><h2>{title} <small>({list.length})</small></h2>{list.length===0?<p className="empty">Geen items.</p>:groupIndex===3?<div className="box"><div className="flex flex-wrap gap-2">{list.map((c,i)=><span key={(c.rule_id||c.title)+i} className="status pass">✓ {c.title}</span>)}</div><p className="meta">Niet van toepassing op deze pagina; deze controles tellen niet mee in de score.</p></div>:groupIndex===1?<div className="box"><div className="flex flex-wrap gap-2">{list.map((c,i)=><span key={(c.rule_id||c.title)+i} className="status pass">✓ {c.title}</span>)}</div></div>:groupIndex===2?<div className="box">{list.map((c,i)=><details key={(c.rule_id||c.title)+i} className="diagnostic-block"><summary><b>? {c.title}</b></summary><p>{c.message}</p>{c.fix&&<p><b>{deep.next}:</b> {c.fix}</p>}</details>)}</div>:list.map((c,i)=><article className="finding" key={(c.rule_id||c.title)+i}><div className="finding-head"><h3>{c.title}</h3><span className={"status "+c.status}>{t.labels[c.status]||c.status}</span></div><p>{c.message}</p>{c.fix&&<p><b>{deep.next}:</b> {c.fix}</p>}<p className="meta">{deep.rule}: {c.rule_id||c.issue_id||c.key||"—"} · {deep.category} {c.category||"—"} · {deep.confidence} {c.confidence||"—"}{c.maxPoints!==undefined?" · punten "+(c.points??0)+"/"+c.maxPoints:""}</p>{c.evidence?.details&&<p className="evidence"><b>{deep.evidence}:</b> {c.evidence.details}</p>}</article>)}</section>)}
    {(sector?.sector==="ecommerce"||sector?.key==="ecommerce"||profile?.isCommerce)&&<section><h2>{deep.commerce}</h2><div className="box">
      {[
        ["Product Optimizer",r.metrics?.productOptimizer],
        ["Prijs & valuta",r.metrics?.pricingCurrency],
        ["EU-Omnibus & Consumer Rights",r.metrics?.euConsumerSignals],
        ["Checkout & funnel",r.metrics?.checkoutFunnel]
      ].map(([title,data]:any)=><div key={title} className="diagnostic-block"><h3>{title}</h3>{data&&typeof data==="object"?Object.entries(data).map(([key,value])=><p key={key}><b>{key}:</b> {Array.isArray(value)?(value.length?value.map(v=>typeof v==="object"?JSON.stringify(v):String(v)).join(" · "):"—"):value&&typeof value==="object"?JSON.stringify(value):value===true?"Ja":value===false?"Nee":value==null?"—":String(value)}</p>):<p>{deep.noData}</p>}</div>)}
    </div></section>}
    <section><h2>{deep.technical}</h2><div className="box"><p><b>{deep.page}:</b> {scan.scanned_url}</p><p><b>{deep.reportId}:</b> {scan.id||id}</p><p><b>Rendering:</b> {rendering?.mode||"—"} · JavaScript: {String(rendering?.javascriptExecuted??false)}</p><p><b>{deep.pageProof}:</b> {(pageType?.evidence||[]).join(" · ")||"Niet beschikbaar"}</p></div></section>
    <footer>RankFix AI · Dit rapport beschrijft wat tijdens deze scan aantoonbaar was. Niet te bevestigen en N.v.t. verlagen de score niet. EU/Omnibus-signalen zijn geen juridische conformiteitsverklaring.</footer>
  </main>;
}
