"use client";
import Link from "next/link";\nimport { useEffect, useState } from "react";
import AiAssistant from "@/components/ai-assistant";
import DashboardNav from "../nav";
import type { Locale } from "@/lib/locales";
import "../dashboard.css";

type Topic={id:string;title:string;body:string;video?:boolean;href?:string};
const labels:Record<Locale,{title:string;intro:string;ai:string;aiBody:string;read:string;video:string;videoSoon:string;open:string;topics:Topic[]}>={
nl:{title:"Helpcentrum",intro:"Alle uitleg voor RankFix op één plek. Begin met de korte uitleg, vraag AI om hulp en gebruik alleen bij moeilijke handelingen een korte video.",ai:"🤖 Vraag RankFix",aiBody:"AI kan je scan en het gekozen probleem uitleggen en vertelt precies wat je volgende stap is.",read:"Uitleg",video:"Korte video",videoSoon:"Video wordt toegevoegd",open:"Open",topics:[
{id:"getting-started",title:"Starten met RankFix",body:"Voer je website in, start een scan en open daarna de verbeterpunten. RankFix laat per probleem zien wat er mis is, waarom het belangrijk is en hoe je verdergaat."},
{id:"scans",title:"Scans en scores",body:"Een score is een momentopname. Alleen bewezen en toepasselijke controles tellen mee. Een fix is pas opgelost wanneer een nieuwe live scan dit bevestigt."},
{id:"problem-solving",title:"Problemen oplossen",body:"Ieder probleem krijgt een route: fix, GitHub-fix, koppeling, klantgegevens of begeleide stappen. Geen probleem hoort zonder vervolgstap te eindigen."},
{id:"ai-fixes",title:"fixes",body:"AI maakt een voorstel dat je eerst kunt bekijken. RankFix verandert niet stilletjes je live website. Na publicatie controleert een nieuwe scan het resultaat."},
{id:"github-connect",title:"GitHub koppelen",body:"Koppel GitHub, kies één keer de repository van je website en laat RankFix daarna branch, bestand en technische context bepalen.",video:true,href:"/dashboard/github"},
{id:"github-pr",title:"GitHub-fix en Pull Request",body:"Bekijk eerst de diff-preview. Na jouw goedkeuring maakt RankFix een aparte Pull Request. Er wordt niets automatisch naar productie gemerged.",video:true,href:"/dashboard/github"},
{id:"search-console",title:"Google Search Console",body:"Koppel Search Console om beschikbare zoekprestatiegegevens in RankFix te gebruiken. AI helpt daarna de gegevens in gewone taal te begrijpen.",video:true,href:"/dashboard/search-console"},
{id:"merchant-center",title:"Merchant Center en Google-koppelingen",body:"Voor webshops toont RankFix alleen de koppeling wanneer die nodig is. De klant krijgt dan korte stappen en waar nodig een video.",video:true},
{id:"shops",title:"Shopify, WooCommerce en webshops",body:"RankFix herkent waar mogelijk het platform. Als externe autorisatie nodig is, krijg je begeleide stappen; ingewikkelde koppelingen krijgen een korte video.",video:true},
{id:"meta-title",title:"Meta title",body:"RankFix controleert of de paginatitel ontbreekt, te kort, te lang of onvoldoende duidelijk is. Bij een veilige AI-route krijg je eerst een voorstel; publiceer pas na controle en bevestig het resultaat met een nieuwe scan."},
{id:"meta-description",title:"Meta description",body:"RankFix controleert aanwezigheid en bruikbare lengte. AI kan een voorstel maken op basis van bewezen pagina-inhoud. Controleer de tekst voordat je hem publiceert."},
{id:"headings",title:"H1 en heading-structuur",body:"RankFix controleert de hoofdheading en structuur van H2/H3. Een voorstel gebruikt alleen bekende pagina-inhoud en moet vóór publicatie worden gecontroleerd."},
{id:"image-alt",title:"Afbeeldingen en alt-tekst",body:"RankFix meldt ontbrekende relevante alt-teksten. Een voorstel moet passen bij wat werkelijk op de afbeelding staat; controleer dit visueel voordat je publiceert."},
{id:"structured-data",title:"Structured data en schema",body:"RankFix controleert bruikbare schema-markup en maakt alleen voorstellen met gegevens die tijdens de scan zijn bevestigd. Verzonnen bedrijfsgegevens zijn niet toegestaan."},
{id:"social-metadata",title:"Social metadata",body:"RankFix controleert Open Graph-signalen en gebruikt bestaande titel, description en afbeeldingen waar beschikbaar. Ontbrekende code kan via de veilige GitHub-flow worden voorgesteld."},
{id:"canonical",title:"Canonical URL",body:"RankFix controleert of de canonical logisch overeenkomt met de bedoelde pagina. Een codewijziging gaat via preview en goedkeuring voordat een Pull Request wordt gemaakt."},
{id:"business-details",title:"Bedrijfsgegevens",body:"Ontbrekende bedrijfsgegevens kunnen niet veilig worden verzonnen. RankFix vraagt alleen de noodzakelijke gegevens aan de klant en gebruikt ze daarna in de juiste fixroute."},
{id:"seo-geo",title:"SEO, GEO en AI Search",body:"RankFix combineert technische SEO met signalen die zoekmachines en AI-systemen helpen de pagina te begrijpen. Elk bevestigd probleem krijgt bewijs, uitleg en een passende vervolgstap."},
{id:"broken-links",title:"Broken links",body:"RankFix toont welke link niet goed reageert en waar die is gevonden. Controleer het juiste doel voordat je de URL vervangt of verwijdert en scan daarna opnieuw."},
{id:"redirects",title:"Redirects",body:"RankFix legt uit welke redirect aandacht nodig heeft. Pas redirects alleen aan als het gewenste eindadres zeker is en controleer daarna opnieuw om loops of verkeerde bestemmingen te voorkomen."},
{id:"links",title:"Technische SEO en toegankelijkheid",body:"Voor technische controles, interne links, indexeerbaarheid en toegankelijkheid toont RankFix het bewijs en een veilige vervolgstap. AI kan de technische uitleg vereenvoudigen."},
{id:"local-seo",title:"Local SEO",body:"RankFix gebruikt alleen bevestigde bedrijfs- en locatiegegevens. Als gegevens ontbreken, vraagt RankFix ze eerst in plaats van een adres, telefoonnummer of openingstijden te verzinnen."},
{id:"ads-analytics",title:"Ads, Analytics en Consent Mode",body:"RankFix controleert alleen wat technisch aantoonbaar is. Externe accounts of toestemmingsinstellingen worden niet als actief gemeld zonder bevestiging."},
{id:"competitors",title:"Concurrenten",body:"Concurrentie-inzichten zijn context voor verbeteringen en geen garantie op ranking. RankFix scheidt gemeten websitegegevens van aanbevelingen."},
{id:"history",title:"Historie en bevestigde fixes",body:"Gebruik historie om scans te vergelijken. Een voorstel of Pull Request is nog niet opgelost; pas een nieuwe live scan kan een fix als bevestigd opgelost markeren."},
{id:"account",title:"Account en problemen oplossen",body:"Bij een fout vertelt RankFix of het om je account, RankFix, GitHub of een blokkade van de gescande website gaat. Zo weet je welke vervolgstap nodig is."}
]},
en:{title:"Help center",intro:"All RankFix help in one place. Read the short explanation, ask AI, and use a short video only for difficult actions.",ai:"🤖 Ask RankFix",aiBody:"AI can explain your scan and selected issue and tell you the exact next step.",read:"Explanation",video:"Short video",videoSoon:"Video will be added",open:"Open",topics:[]},
de:{title:"Hilfe-Center",intro:"Alle RankFix-Hilfe an einem Ort. Kurze Erklärung lesen, AI fragen und Videos nur für schwierige Schritte nutzen.",ai:"🤖 RankFix fragen",aiBody:"AI erklärt Scan und Problem und nennt den nächsten Schritt.",read:"Erklärung",video:"Kurzes Video",videoSoon:"Video wird hinzugefügt",open:"Öffnen",topics:[]},
fr:{title:"Centre d’aide",intro:"Toute l’aide RankFix au même endroit. Lisez l’explication, demandez à l’IA et utilisez une vidéo seulement pour les étapes difficiles.",ai:"🤖 Demander à RankFix",aiBody:"L’IA explique l’analyse et le problème sélectionné puis indique l’étape suivante.",read:"Explication",video:"Vidéo courte",videoSoon:"Vidéo à venir",open:"Ouvrir",topics:[]},
it:{title:"Centro assistenza",intro:"Tutto l’aiuto RankFix in un unico posto. Leggi la spiegazione, chiedi all’AI e usa i video solo per i passaggi difficili.",ai:"🤖 Chiedi a RankFix",aiBody:"L’AI spiega scansione e problema e indica il prossimo passo.",read:"Spiegazione",video:"Video breve",videoSoon:"Video in arrivo",open:"Apri",topics:[]},
es:{title:"Centro de ayuda",intro:"Toda la ayuda de RankFix en un solo lugar. Lee la explicación, pregunta a la IA y usa vídeo solo para pasos difíciles.",ai:"🤖 Pregunta a RankFix",aiBody:"La IA explica el análisis y el problema y te indica el siguiente paso.",read:"Explicación",video:"Vídeo corto",videoSoon:"Vídeo próximamente",open:"Abrir",topics:[]}
};
const fallbackTitles:Record<Exclude<Locale,"nl">,string[]>={
en:["Getting started with RankFix","Scans and scores","Fixing problems","Fixes","Connect GitHub","GitHub fix and Pull Request","Google Search Console","Merchant Center and Google connections","Shopify, WooCommerce and stores","SEO, GEO and content","Broken links, redirects and technical","Account, history and troubleshooting"],
de:["Mit RankFix starten","Scans und Scores","Probleme beheben","Fixes","GitHub verbinden","GitHub-Fix und Pull Request","Google Search Console","Merchant Center und Google-Verbindungen","Shopify, WooCommerce und Shops","SEO, GEO und Inhalte","Defekte Links, Weiterleitungen und Technik","Konto, Verlauf und Fehlerbehebung"],
fr:["Bien démarrer avec RankFix","Analyses et scores","Corriger les problèmes","Correctifs","Connecter GitHub","Correctif GitHub et Pull Request","Google Search Console","Merchant Center et connexions Google","Shopify, WooCommerce et boutiques","SEO, GEO et contenu","Liens cassés, redirections et technique","Compte, historique et dépannage"],
it:["Iniziare con RankFix","Scansioni e punteggi","Risolvere i problemi","Fix","Collega GitHub","Fix GitHub e Pull Request","Google Search Console","Merchant Center e collegamenti Google","Shopify, WooCommerce e negozi","SEO, GEO e contenuti","Link interrotti, redirect e tecnica","Account, cronologia e problemi"],
es:["Empezar con RankFix","Análisis y puntuaciones","Resolver problemas","Correcciones","Conectar GitHub","Corrección GitHub y Pull Request","Google Search Console","Merchant Center y conexiones de Google","Shopify, WooCommerce y tiendas","SEO, GEO y contenido","Enlaces rotos, redirecciones y técnica","Cuenta, historial y problemas"]
};
const localizedBodies:Record<Exclude<Locale,"nl">,string[]>={
en:["Enter your website, run a scan and open the improvements. RankFix shows what is wrong and what to do next.","A score is a snapshot. A fix is only solved after a new live scan confirms it.","Every issue gets a route: AI fix, GitHub fix, connection, customer input or guided steps.","AI prepares a proposal for review. RankFix does not silently change your live website.","Connect GitHub and choose the repository once. RankFix then uses the verified website-repository link.","Review the diff first. After approval RankFix creates a separate Pull Request; nothing is merged automatically.","Connect Search Console to use available search performance data and let AI explain it simply.","Store integrations are shown only when needed, with guided steps and video where useful.","RankFix detects the platform where possible and guides external authorization when required.","Titles, descriptions, headings, alt text, structured data and AI-search signals get clear guidance and a safe fix route where possible.","RankFix shows evidence, the recommended change and how to verify it again.","Use history to compare scans. Errors clearly distinguish RankFix, account, GitHub and target-site blocks."],
de:["Website eingeben, Scan starten und Verbesserungen öffnen. RankFix zeigt Problem und nächsten Schritt.","Ein Score ist eine Momentaufnahme. Ein Fix gilt erst nach Bestätigung durch einen neuen Live-Scan als gelöst.","Jedes Problem erhält einen Weg: Fix, GitHub-Fix, Verbindung, Kundendaten oder geführte Schritte.","AI erstellt einen Vorschlag zur Prüfung. RankFix ändert die Live-Website nicht stillschweigend.","GitHub verbinden und Repository einmal auswählen. Danach nutzt RankFix die bestätigte Verknüpfung.","Zuerst Diff prüfen. Nach Freigabe erstellt RankFix einen separaten Pull Request; nichts wird automatisch gemergt.","Search Console verbinden, um verfügbare Suchdaten zu nutzen und von AI erklären zu lassen.","Shop-Verbindungen erscheinen nur wenn nötig, mit Schritten und bei Bedarf Video.","RankFix erkennt das System soweit möglich und führt durch nötige externe Autorisierung.","Titles, Descriptions, Überschriften, Alt-Texte, strukturierte Daten und AI-Suche erhalten klare Fixwege.","RankFix zeigt Nachweis, empfohlene Änderung und erneute Kontrolle.","Verlauf zum Vergleichen nutzen. Fehler unterscheiden RankFix, Konto, GitHub und Zielwebsite."],
fr:["Saisissez le site, lancez l’analyse puis ouvrez les améliorations. RankFix indique le problème et l’étape suivante.","Un score est un instantané. Un correctif n’est résolu qu’après confirmation par une nouvelle analyse en ligne.","Chaque problème reçoit une voie : IA, GitHub, connexion, données client ou étapes guidées.","L’IA prépare une proposition à vérifier. RankFix ne modifie pas silencieusement le site en ligne.","Connectez GitHub et choisissez le dépôt une seule fois. RankFix utilise ensuite cette association vérifiée.","Vérifiez d’abord le diff. Après validation, RankFix crée une Pull Request séparée sans fusion automatique.","Connectez Search Console pour utiliser les données disponibles et laisser l’IA les expliquer simplement.","Les connexions e-commerce apparaissent seulement si nécessaire, avec étapes et vidéo utile.","RankFix détecte la plateforme si possible et guide l’autorisation externe nécessaire.","Titres, descriptions, Hn, textes alt, données structurées et signaux IA reçoivent une voie claire.","RankFix montre la preuve, la modification recommandée et comment la vérifier à nouveau.","Utilisez l’historique pour comparer. Les erreurs distinguent RankFix, compte, GitHub et blocage du site cible."],
it:["Inserisci il sito, avvia la scansione e apri i miglioramenti. RankFix mostra problema e prossimo passo.","Il punteggio è un’istantanea. Un fix è risolto solo dopo la conferma di una nuova scansione live.","Ogni problema ha un percorso: AI, GitHub, collegamento, dati cliente o passaggi guidati.","L’AI prepara una proposta da controllare. RankFix non modifica silenziosamente il sito live.","Collega GitHub e scegli il repository una volta. RankFix userà poi il collegamento verificato.","Controlla prima il diff. Dopo l’approvazione RankFix crea una Pull Request separata senza merge automatico.","Collega Search Console per usare i dati disponibili e farli spiegare dall’AI.","I collegamenti e-commerce appaiono solo quando servono, con passaggi e video se utile.","RankFix rileva la piattaforma quando possibile e guida l’autorizzazione esterna necessaria.","Titoli, description, heading, alt, dati strutturati e segnali AI ricevono un percorso chiaro.","RankFix mostra prove, modifica consigliata e come verificarla di nuovo.","Usa la cronologia per confrontare. Gli errori distinguono RankFix, account, GitHub e sito target."],
es:["Introduce la web, inicia el análisis y abre las mejoras. RankFix muestra el problema y el siguiente paso.","La puntuación es una instantánea. Una corrección solo queda resuelta tras confirmarla con un nuevo análisis en vivo.","Cada problema tiene una ruta: IA, GitHub, conexión, datos del cliente o pasos guiados.","La IA prepara una propuesta para revisar. RankFix no cambia silenciosamente la web en vivo.","Conecta GitHub y elige el repositorio una vez. RankFix usará después ese vínculo verificado.","Revisa primero el diff. Tras aprobarlo RankFix crea una Pull Request separada sin fusión automática.","Conecta Search Console para usar los datos disponibles y dejar que la IA los explique.","Las conexiones de tienda aparecen solo cuando hacen falta, con pasos y vídeo cuando sea útil.","RankFix detecta la plataforma cuando es posible y guía la autorización externa necesaria.","Títulos, descripciones, encabezados, alt, datos estructurados y señales de IA reciben una ruta clara.","RankFix muestra evidencia, cambio recomendado y cómo volver a verificarlo.","Usa el historial para comparar. Los errores distinguen RankFix, cuenta, GitHub y bloqueo del sitio objetivo."]
};
function localizedTopics(language:Locale):Topic[]{
 const base=labels.nl.topics;
 if(language==="nl") return base;
 const titles=fallbackTitles[language], bodies=localizedBodies[language];
 return base.map((x,i)=>({...x,title:titles[i],body:bodies[i]}));
}
export default function HelpPage(){
 const [open,setOpen]=useState<string>("getting-started"); const [language,setLanguage]=useState<Locale>("nl");
 useEffect(()=>{fetch("/api/account/language").then(r=>r.ok?r.json():null).then(d=>{if(d?.language&&d.language in labels)setLanguage(d.language)}).catch(()=>{})},[]);
 useEffect(()=>{const id=location.hash.slice(1);if(id)setOpen(id)},[]);
 const t=labels[language]; const topics=localizedTopics(language);
 return <main className="rf-page" lang={language}><div className="rf-shell"><header className="rf-header"><Link href="/" className="rf-brand">RankFix</Link></header><DashboardNav/><div className="rf-body">
 <div className="rf-heading"><h1>{t.title}</h1><p>{t.intro}</p></div>
 <section className="rf-help-ai"><strong>{t.ai}</strong><p>{t.aiBody}</p></section>
 <div className="rf-help-grid">{topics.map(topic=><section id={topic.id} key={topic.id} className="rf-help-topic"><button type="button" onClick={()=>setOpen(open===topic.id?"":topic.id)} aria-expanded={open===topic.id}><span><b>{topic.title}</b><em>{open===topic.id?"−":"+"}</em></span></button>{open===topic.id&&<div><p>{topic.body}</p><div className="mt-3 flex flex-wrap gap-2">{topic.href&&<Link className="rf-primary-link" href={topic.href}>{t.open} →</Link>}{topic.video&&<span className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-400">▶ {t.video} · {t.videoSoon}</span>}</div></div>}</section>)}</div>
 </div></div><AiAssistant dashboard/></main>
}
