"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import AiAssistant from "@/components/ai-assistant";
import DashboardNav from "../nav";
import type { Locale } from "@/lib/locales";
import "../dashboard.css";

const copy:Record<Locale,{title:string;intro:string;ask:string;askBody:string;steps:string;stepBody:string;openGithub:string;topics:string[][]}> = {
nl:{title:"Helpcentrum",intro:"Alles wat je nodig hebt om RankFix te gebruiken, zonder technische kennis.",ask:"🤖 Vraag RankFix AI",askBody:"Vraag bijvoorbeeld waarom je score lager is, wat je eerst moet oplossen of hoe je GitHub koppelt. Gebruik de AI-knop rechtsonder.",steps:"GitHub in 5 eenvoudige stappen",stepBody:"1. GitHub koppelen → 2. Repository kiezen → 3. RankFix maakt een fix → 4. Jij publiceert → 5. RankFix scant opnieuw",openGithub:"Open GitHub-koppeling →",topics:[["Scans en scores","Je RankFix-score laat zien hoe je website ervoor staat. Open een scan voor SEO, GEO en concrete verbeterpunten."],["Problemen oplossen","Begin bij de belangrijkste verbeterpunten. RankFix legt in gewone taal uit wat er mis is en wat de volgende stap is."],["AI-fixes","Een AI-fix is een voorstel. Een wijziging telt pas als opgelost nadat deze is gepubliceerd en een nieuwe live scan de verbetering bevestigt."],["GitHub koppelen","Koppel je account, kies de repository, laat RankFix een voorstel maken, controleer/publiceer het en scan opnieuw."],["Abonnementen","AI-fixes zijn inbegrepen volgens je RankFix-abonnement. Je ziet vooraf welke functies bij je pakket horen."],["Rapporten en historie","Gebruik je scanhistorie om oude en nieuwe resultaten te vergelijken en rapporten te bewaren of delen."]]},
en:{title:"Help center",intro:"Everything you need to use RankFix, without technical knowledge.",ask:"🤖 Ask RankFix AI",askBody:"Ask why your score is lower, what to fix first, or how to connect GitHub. Use the AI button at the bottom right.",steps:"GitHub in 5 simple steps",stepBody:"1. Connect GitHub → 2. Choose repository → 3. RankFix creates a fix → 4. You publish → 5. RankFix scans again",openGithub:"Open GitHub connection →",topics:[["Scans and scores","Your RankFix score shows how your website is doing. Open a scan for SEO, GEO and concrete improvements."],["Fixing problems","Start with the most important improvements. RankFix explains the issue and next step in plain language."],["AI fixes","An AI fix is a proposal. A change counts as solved only after publication and a new live scan confirms it."],["Connect GitHub","Connect your account, choose the repository, let RankFix create a proposal, review/publish it and scan again."],["Plans","AI fixes are included according to your RankFix plan. You can see which features your plan includes."],["Reports and history","Use scan history to compare results and save or share reports."]]},
de:{title:"Hilfe-Center",intro:"Alles, was du für RankFix brauchst – ohne technische Vorkenntnisse.",ask:"🤖 RankFix AI fragen",askBody:"Frage, warum dein Score niedriger ist, was du zuerst beheben solltest oder wie GitHub verbunden wird. Nutze den AI-Button unten rechts.",steps:"GitHub in 5 einfachen Schritten",stepBody:"1. GitHub verbinden → 2. Repository wählen → 3. RankFix erstellt einen Fix → 4. Du veröffentlichst → 5. RankFix scannt erneut",openGithub:"GitHub-Verbindung öffnen →",topics:[["Scans und Scores","Dein RankFix-Score zeigt den Zustand deiner Website. Öffne einen Scan für SEO, GEO und konkrete Verbesserungen."],["Probleme beheben","Beginne mit den wichtigsten Verbesserungen. RankFix erklärt Problem und nächsten Schritt verständlich."],["AI-Fixes","Ein AI-Fix ist ein Vorschlag. Erst nach Veröffentlichung und bestätigendem Live-Scan gilt die Änderung als gelöst."],["GitHub verbinden","Verbinde dein Konto, wähle das Repository, lasse RankFix einen Vorschlag erstellen, prüfe/veröffentliche ihn und scanne erneut."],["Abonnements","AI-Fixes sind entsprechend deinem RankFix-Paket enthalten."],["Berichte und Verlauf","Nutze den Scanverlauf zum Vergleichen und zum Speichern oder Teilen von Berichten."]]},
fr:{title:"Centre d’aide",intro:"Tout ce qu’il faut pour utiliser RankFix, sans connaissances techniques.",ask:"🤖 Demander à RankFix AI",askBody:"Demandez pourquoi votre score est plus bas, quoi corriger en premier ou comment connecter GitHub. Utilisez le bouton AI en bas à droite.",steps:"GitHub en 5 étapes simples",stepBody:"1. Connecter GitHub → 2. Choisir le dépôt → 3. RankFix crée un correctif → 4. Vous publiez → 5. RankFix analyse à nouveau",openGithub:"Ouvrir la connexion GitHub →",topics:[["Analyses et scores","Votre score RankFix montre l’état de votre site. Ouvrez une analyse pour le SEO, le GEO et les améliorations concrètes."],["Corriger les problèmes","Commencez par les améliorations les plus importantes. RankFix explique le problème et la prochaine étape simplement."],["Correctifs AI","Un correctif AI est une proposition. Il est résolu seulement après publication et confirmation par une nouvelle analyse."],["Connecter GitHub","Connectez votre compte, choisissez le dépôt, laissez RankFix proposer un correctif, vérifiez/publiez puis analysez à nouveau."],["Abonnements","Les correctifs AI sont inclus selon votre abonnement RankFix."],["Rapports et historique","Utilisez l’historique pour comparer les résultats et conserver ou partager les rapports."]]},
it:{title:"Centro assistenza",intro:"Tutto ciò che serve per usare RankFix, senza conoscenze tecniche.",ask:"🤖 Chiedi a RankFix AI",askBody:"Chiedi perché il punteggio è più basso, cosa correggere prima o come collegare GitHub. Usa il pulsante AI in basso a destra.",steps:"GitHub in 5 semplici passaggi",stepBody:"1. Collega GitHub → 2. Scegli repository → 3. RankFix crea un fix → 4. Pubblica → 5. RankFix esegue una nuova scansione",openGithub:"Apri collegamento GitHub →",topics:[["Scansioni e punteggi","Il punteggio RankFix mostra lo stato del sito. Apri una scansione per SEO, GEO e miglioramenti concreti."],["Risolvere problemi","Inizia dai miglioramenti più importanti. RankFix spiega problema e passo successivo in modo semplice."],["Fix AI","Un fix AI è una proposta. È risolto solo dopo la pubblicazione e la conferma di una nuova scansione live."],["Collega GitHub","Collega l’account, scegli il repository, lascia creare una proposta a RankFix, controlla/pubblica e scansiona di nuovo."],["Abbonamenti","I fix AI sono inclusi in base al tuo piano RankFix."],["Report e cronologia","Usa la cronologia per confrontare i risultati e salvare o condividere i report."]]},
es:{title:"Centro de ayuda",intro:"Todo lo que necesitas para usar RankFix, sin conocimientos técnicos.",ask:"🤖 Pregunta a RankFix AI",askBody:"Pregunta por qué tu puntuación es más baja, qué corregir primero o cómo conectar GitHub. Usa el botón AI de abajo a la derecha.",steps:"GitHub en 5 pasos sencillos",stepBody:"1. Conecta GitHub → 2. Elige repositorio → 3. RankFix crea una corrección → 4. Publicas → 5. RankFix vuelve a analizar",openGithub:"Abrir conexión de GitHub →",topics:[["Análisis y puntuaciones","Tu puntuación RankFix muestra el estado de tu web. Abre un análisis para SEO, GEO y mejoras concretas."],["Resolver problemas","Empieza por las mejoras más importantes. RankFix explica el problema y el siguiente paso de forma sencilla."],["Correcciones AI","Una corrección AI es una propuesta. Solo se considera resuelta tras publicarla y confirmarla con un nuevo análisis."],["Conectar GitHub","Conecta tu cuenta, elige el repositorio, deja que RankFix cree una propuesta, revísala/publícala y analiza de nuevo."],["Planes","Las correcciones AI están incluidas según tu plan RankFix."],["Informes e historial","Usa el historial para comparar resultados y guardar o compartir informes."]]}
};
export default function HelpPage(){
 const [open,setOpen]=useState<number|null>(0); const [language,setLanguage]=useState<Locale>("nl");
 useEffect(()=>{fetch("/api/account/language").then(r=>r.ok?r.json():null).then(d=>{if(d?.language&&d.language in copy)setLanguage(d.language)}).catch(()=>{})},[]);
 const t=copy[language];
 return <main className="rf-page" lang={language}><div className="rf-shell"><header className="rf-header"><Link href="/" className="rf-brand" aria-label="RankFix AI home">RankFix <span>AI</span></Link></header><DashboardNav/><div className="rf-body"><div className="rf-heading"><h1 className="text-3xl sm:text-4xl">{t.title}</h1><p className="text-base sm:text-lg">{t.intro}</p></div><section className="rf-help-ai"><strong className="text-lg">{t.ask}</strong><p className="text-base leading-7">{t.askBody}</p><button type="button" className="rf-help-ai-button" onClick={()=>window.dispatchEvent(new Event("rankfix-open-ai"))}>{language==="nl"?"Open RankFix AI":language==="de"?"RankFix AI öffnen":language==="fr"?"Ouvrir RankFix AI":language==="it"?"Apri RankFix AI":language==="es"?"Abrir RankFix AI":"Open RankFix AI"}</button><p className="mt-3 text-sm text-slate-400">RankFix AI gebruikt binnen het dashboard jouw eigen scancontext om scores, bewezen problemen en vervolgstappen uit te leggen. Andere klantgegevens en interne secrets zijn niet toegankelijk.</p></section><nav className="rf-help-shortcuts" aria-label="Help onderwerpen"><a href="#help-topics">Scans & audit</a><a href="#help-github">GitHub</a><a href="#help-videos">Video-uitleg</a><Link href="/dashboard/search-console">Search Console</Link></nav><div id="help-topics" className="rf-help-grid">{t.topics.map(([title,body],i)=><button key={title} className="rf-help-topic" onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}><span><b className="text-base sm:text-lg">{title}</b><em>{open===i?"−":"+"}</em></span>{open===i&&<p className="text-base leading-7">{body}</p>}</button>)}</div><section id="help-github" className="rf-github-steps"><h2>{t.steps}</h2><div>{t.stepBody}</div><Link href="/dashboard/github">{t.openGithub}</Link></section><section id="help-videos" className="rf-help-videos"><span className="rf-eyebrow">Korte uitlegvideo’s</span><h2>Ingewikkeld? Bekijk het stap voor stap.</h2><p>Hier komen korte video’s voor GitHub koppelen, Search Console koppelen, een fix publiceren, monitoring instellen en je audit begrijpen.</p><div className="rf-help-video-grid">{["GitHub koppelen","Search Console koppelen","Fix publiceren","Audit begrijpen"].map(x=><article key={x}><div className="rf-video-placeholder"><span>▶</span></div><strong>{x}</strong><small>Video in voorbereiding</small></article>)}</div></section></div></div><AiAssistant dashboard/></main>
}