"use client";
import { useEffect,useState } from "react";
import DashboardNav from "../nav";
import AiAssistant from "@/components/ai-assistant";
import type { Locale } from "@/lib/locales";
import { getFixDefinition, helpHref } from "@/lib/fix-routing";
import "../dashboard.css";

type Issue={category?:string;title?:string;status?:string;message?:string;fix?:string;issue_id?:string;rule_id?:string;severity?:string;confidence?:string};
type Scan={id:string;scanned_url:string;final_url?:string;created_at:string};
type FixState={issue_id:string;status:string;repository?:string;pr_number?:number};
const copy:Record<Locale,{title:string;intro:string;loading:string;empty:string;emptyBody:string;scan:string;issue:string;route:string;ai:string;github:string;guided:string;open:string;help:string;rescan:string;verify:string;evidence:string;count:(n:number)=>string;integration:string;customer:string;statusPrepared:string;statusPr:string;statusPublication:string;statusVerification:string;statusDone:string;active:string;githubConnected:string;githubConnect:string}>={
nl:{title:"Fixes",intro:"Van probleem naar oplossing. RankFix laat per verbeterpunt zien welke veilige vervolgstap beschikbaar is.",loading:"Fixes laden…",empty:"Geen open fixes",emptyBody:"De nieuwste scan bevat geen bevestigde verbeterpunten die nu actie vragen.",scan:"Nieuwste scan",issue:"Verbeterpunt",route:"Oplossing",ai:"AI-fix",github:"GitHub-fix",guided:"Begeleide oplossing",open:"Open fix",help:"Bekijk stappen",rescan:"Nieuwe scan",verify:"Herscan & controleer fixes",evidence:"Eerst bekijken, daarna toepassen en opnieuw scannen.",count:n=>`${n} ${n===1?"verbeterpunt":"verbeterpunten"}`,integration:"Koppeling nodig",customer:"Gegevens nodig",statusPrepared:"Voorstel voorbereid",statusPr:"Pull Request gemaakt",statusPublication:"Wacht op publicatie door jou",statusVerification:"Wacht op herscan",statusDone:"✓ Bevestigd opgelost",active:"Lopende fixes",githubConnected:"✓ GitHub gekoppeld",githubConnect:"GitHub koppelen"},
en:{title:"Fixes",intro:"From issue to solution. RankFix shows the safe next step for every improvement.",loading:"Loading fixes…",empty:"No open fixes",emptyBody:"The latest scan has no confirmed improvements that currently need action.",scan:"Latest scan",issue:"Improvement",route:"Solution",ai:"AI fix",github:"GitHub fix",guided:"Guided solution",open:"Open fix",help:"View steps",rescan:"New scan",verify:"Rescan & verify fixes",evidence:"Review first, then apply and scan again.",count:n=>`${n} ${n===1?"improvement":"improvements"}`,integration:"Connection required",customer:"Information required",statusPrepared:"Proposal prepared",statusPr:"Pull Request created",statusPublication:"Waiting for you to publish",statusVerification:"Waiting for rescan",statusDone:"✓ Confirmed resolved",active:"Active fixes",githubConnected:"✓ GitHub connected",githubConnect:"Connect GitHub"},
de:{title:"Fixes",intro:"Vom Problem zur Lösung. RankFix zeigt für jede Verbesserung den sicheren nächsten Schritt.",loading:"Fixes werden geladen…",empty:"Keine offenen Fixes",emptyBody:"Der neueste Scan enthält keine bestätigten Verbesserungen, die jetzt eine Aktion benötigen.",scan:"Neuester Scan",issue:"Verbesserung",route:"Lösung",ai:"AI-Fix",github:"GitHub-Fix",guided:"Geführte Lösung",open:"Fix öffnen",help:"Schritte ansehen",rescan:"Neuer Scan",verify:"Neu scannen & Fixes prüfen",evidence:"Zuerst prüfen, dann anwenden und erneut scannen.",count:n=>`${n} ${n===1?"Verbesserung":"Verbesserungen"}`,integration:"Verbindung erforderlich",customer:"Angaben erforderlich",statusPrepared:"Vorschlag vorbereitet",statusPr:"Pull Request erstellt",statusPublication:"Wartet auf deine Veröffentlichung",statusVerification:"Wartet auf erneuten Scan",statusDone:"✓ Als gelöst bestätigt",active:"Laufende Fixes",githubConnected:"✓ GitHub verbunden",githubConnect:"GitHub verbinden"},
fr:{title:"Correctifs",intro:"Du problème à la solution. RankFix indique l’étape sûre pour chaque amélioration.",loading:"Chargement des correctifs…",empty:"Aucun correctif ouvert",emptyBody:"La dernière analyse ne contient aucune amélioration confirmée nécessitant une action.",scan:"Dernière analyse",issue:"Amélioration",route:"Solution",ai:"Correctif IA",github:"Correctif GitHub",guided:"Solution guidée",open:"Ouvrir",help:"Voir les étapes",rescan:"Nouvelle analyse",verify:"Réanalyser & vérifier",evidence:"Vérifiez d’abord, appliquez ensuite puis analysez à nouveau.",count:n=>`${n} ${n===1?"amélioration":"améliorations"}`,integration:"Connexion requise",customer:"Informations requises",statusPrepared:"Proposition préparée",statusPr:"Pull Request créée",statusPublication:"En attente de votre publication",statusVerification:"En attente d’une nouvelle analyse",statusDone:"✓ Résolution confirmée",active:"Correctifs en cours",githubConnected:"✓ GitHub connecté",githubConnect:"Connecter GitHub"},
it:{title:"Fix",intro:"Dal problema alla soluzione. RankFix mostra il prossimo passo sicuro per ogni miglioramento.",loading:"Caricamento fix…",empty:"Nessun fix aperto",emptyBody:"L’ultima scansione non contiene miglioramenti confermati che richiedono un’azione.",scan:"Ultima scansione",issue:"Miglioramento",route:"Soluzione",ai:"Fix AI",github:"Fix GitHub",guided:"Soluzione guidata",open:"Apri fix",help:"Vedi passaggi",rescan:"Nuova scansione",verify:"Riscansiona & verifica",evidence:"Prima controlla, poi applica e scansiona di nuovo.",count:n=>`${n} ${n===1?"miglioramento":"miglioramenti"}`,integration:"Collegamento richiesto",customer:"Dati richiesti",statusPrepared:"Proposta preparata",statusPr:"Pull Request creata",statusPublication:"In attesa della tua pubblicazione",statusVerification:"In attesa di una nuova scansione",statusDone:"✓ Risoluzione confermata",active:"Fix in corso",githubConnected:"✓ GitHub collegato",githubConnect:"Collega GitHub"},
es:{title:"Mejoras",intro:"Del problema a la solución. RankFix muestra el siguiente paso seguro para cada mejora.",loading:"Cargando mejoras…",empty:"No hay mejoras abiertas",emptyBody:"El último análisis no contiene mejoras confirmadas que requieran acción.",scan:"Último análisis",issue:"Mejora",route:"Solución",ai:"Corrección IA",github:"Corrección GitHub",guided:"Solución guiada",open:"Abrir",help:"Ver pasos",rescan:"Nuevo análisis",verify:"Reanalizar & verificar",evidence:"Primero revisa, después aplica y vuelve a analizar.",count:n=>`${n} ${n===1?"mejora":"mejoras"}`,integration:"Conexión necesaria",customer:"Datos necesarios",statusPrepared:"Propuesta preparada",statusPr:"Pull Request creada",statusPublication:"Esperando tu publicación",statusVerification:"Esperando un nuevo análisis",statusDone:"✓ Solución confirmada",active:"Mejoras en curso",githubConnected:"✓ GitHub conectado",githubConnect:"Conectar GitHub"}
};
function routeFor(issue:Issue){return getFixDefinition(issue.issue_id||issue.rule_id||"").route}
export default function FixesPage(){
 const [language,setLanguage]=useState<Locale>("nl"),[scan,setScan]=useState<Scan|null>(null),[issues,setIssues]=useState<Issue[]>([]),[fixStates,setFixStates]=useState<Record<string,FixState>>({}),[githubConnected,setGithubConnected]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const pref=await fetch("/api/account/language").then(r=>r.ok?r.json():null);const lang=(pref?.language&&pref.language in copy?pref.language:"nl") as Locale;setLanguage(lang);const gh=await fetch("/api/github/status",{cache:"no-store"});if(gh.ok){const gd=await gh.json();setGithubConnected(Boolean(gd.connected))}const h=await fetch("/api/history",{cache:"no-store"});const hd=await h.json();if(!h.ok)throw new Error(hd.error||"History failed");const latest=hd.history?.[0]||hd.scans?.[0];if(!latest)return;const sr=await fetch("/api/assistant/scan?scanId="+encodeURIComponent(latest.id)+"&language="+lang,{cache:"no-store"});const sd=await sr.json();if(!sr.ok)throw new Error(sd.error||"Fixes failed");setScan(sd.scan);setIssues(sd.issues||[]);const fr=await fetch("/api/fixes?scan_id="+encodeURIComponent(latest.id),{cache:"no-store"});if(fr.ok){const fd=await fr.json();setFixStates(Object.fromEntries((fd.fixes||[]).map((x:FixState)=>[x.issue_id,x]))) }}catch(e){setError(e instanceof Error?e.message:"Fixes failed")}finally{setLoading(false)}})()},[]);
 const t=copy[language];
 const statusLabel=(s?:string)=>s==="DONE"?t.statusDone:s==="PR_CREATED"?t.statusPr:s==="WAITING_PUBLICATION"?t.statusPublication:s==="WAITING_VERIFICATION"?t.statusVerification:s==="PREPARED"?t.statusPrepared:s||"";
 const activeWorkflow=Object.values(fixStates).filter(x=>x.status!=="DONE").length;
 const confirmed=Object.values(fixStates).filter(x=>x.status==="DONE").length;
 return <main className="rf-page" lang={language}><div className="rf-shell"><header className="rf-header"><a href="/dashboard" className="rf-brand">RankFix</a></header><DashboardNav/><div className="rf-body">
  <div className="rf-heading"><h1>{t.title}</h1><p>{t.intro}</p></div>
  {scan&&<><section className="rf-card"><span className="rf-eyebrow">{t.scan}</span><h2>{(()=>{try{return new URL(scan.scanned_url).hostname}catch{return scan.scanned_url}})()}</h2><p>{new Date(scan.created_at).toLocaleString(language)} · {t.count(issues.length)}</p></section><div className="mt-3 grid grid-cols-3 gap-2"><div className="rf-card p-3"><b className="text-lg">{issues.length}</b><p className="text-xs">{t.issue}</p></div><div className="rf-card p-3"><b className="text-lg">{activeWorkflow}</b><p className="text-xs">{t.active}</p></div><div className="rf-card p-3"><b className="text-lg">{confirmed}</b><p className="text-xs">{t.statusDone}</p></div></div></>}
  {loading&&<p className="rf-empty">{t.loading}</p>}{error&&<p className="rf-alert">{error}</p>}
  {!loading&&!error&&issues.length===0&&<section className="rf-card"><h2>{t.empty}</h2><p>{t.emptyBody}</p><a className="rf-primary-link mt-3 inline-flex" href="/dashboard/scan">{t.rescan} →</a></section>}
  {!loading&&!error&&issues.length>0&&<div className="mt-4 grid gap-3">{issues.map((issue,i)=>{const route=routeFor(issue);const q=new URLSearchParams({scan_id:scan?.id||"",issue_id:issue.issue_id||issue.rule_id||""});const state=fixStates[issue.issue_id||issue.rule_id||""];const href=route==="ai"?"/dashboard/ai-fix?"+q.toString():route==="github"?"/dashboard/github?"+q.toString():helpHref(issue.issue_id||issue.rule_id||"");return <article className="rf-card" key={(issue.issue_id||issue.title||"issue")+i}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><span className="rf-eyebrow">{issue.category||t.issue}</span><h2>{issue.title||t.issue}</h2><p className="mt-2">{issue.message}</p>{issue.fix&&<p className="mt-2 text-sm text-slate-400">{issue.fix}</p>}</div><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-bold">{route==="ai"?t.ai:route==="github"?t.github:route==="integration"?t.integration:route==="customer_input"?t.customer:t.guided}</span></div><p className="mt-3 text-xs text-slate-500">{t.evidence}</p>{route==="github"&&<div className="mt-2 text-xs font-semibold">{githubConnected?<span className="text-emerald-200">{t.githubConnected}</span>:<a href="/dashboard/github" className="text-sky-300 underline">{t.githubConnect} →</a>}</div>}{state&&<div className="mt-2 text-xs font-semibold text-emerald-200">{statusLabel(state.status)}{state.pr_number?` · PR #${state.pr_number}`:""}</div>}<a className="rf-primary-link mt-3 inline-flex" href={href}>{route==="ai"||route==="github"?t.open:t.help} →</a></article>})}</div>}
 {!loading&&scan&&<div className="mt-5"><a className="rf-primary-link inline-flex" href={"/dashboard/scan?verify=1&url="+encodeURIComponent(scan.final_url||scan.scanned_url)}>{t.verify} →</a></div>}
 </div></div><AiAssistant dashboard scanId={scan?.id}/></main>
}
