"use client";
import { useEffect,useState } from "react";

const publicIcons=["M3 10l9-7 9 7v10H3z M9 20v-7h6v7","M12 3v18 M3 12h18","M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M12 7v5l3 2","M4 6h16v12H4z M8 10h8 M8 14h5","M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z M9.7 9a2.5 2.5 0 1 1 3.9 2.1c-1 .7-1.6 1.2-1.6 2.4 M12 17h.01"];
const appIcons=["M3 10l9-7 9 7v10H3z M9 20v-7h6v7","M12 3v18 M3 12h18","M14.7 6.3a4 4 0 0 0-5 5L4 17v3h3l5.7-5.7a4 4 0 0 0 5-5l-2.3 2.3-3-3L14.7 6.3z","M4 6h16 M4 12h16 M4 18h10","M12 3v3 M12 18v3 M3 12h3 M18 12h3 M5.6 5.6l2.1 2.1 M16.3 16.3l2.1 2.1 M18.4 5.6l-2.1 2.1 M7.7 16.3l-2.1 2.1 M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"];
const publicLabels:Record<string,string[]>={nl:["Home","Scan","Zo werkt het","Prijzen","Help"],en:["Home","Scan","How it works","Pricing","Help"],de:["Start","Scan","So funktioniert’s","Preise","Hilfe"],fr:["Accueil","Scan","Comment ça marche","Tarifs","Aide"],it:["Home","Analisi","Come funziona","Prezzi","Aiuto"],es:["Inicio","Análisis","Cómo funciona","Precios","Ayuda"]};
const appLabels:Record<string,string[]>={nl:["Overzicht","Scannen","Fixes","Historie","Meer"],en:["Overview","Scan","Fixes","History","More"],de:["Übersicht","Scannen","Fixes","Verlauf","Mehr"],fr:["Aperçu","Scanner","Correctifs","Historique","Plus"],it:["Panoramica","Scansiona","Modifiche","Cronologia","Altro"],es:["Resumen","Escanear","Mejoras","Historial","Más"]};

export default function RootMobileNav({locale="nl"}:{locale?:string}){
 const [signedIn,setSignedIn]=useState(false); const [ready,setReady]=useState(false); const [locationKey,setLocationKey]=useState("");
 useEffect(()=>{fetch("/api/auth/me",{cache:"no-store",credentials:"same-origin"}).then(r=>r.json()).then(d=>{setSignedIn(Boolean(d?.user));setReady(true)}).catch(()=>setReady(true));const sync=()=>setLocationKey(window.location.pathname+window.location.hash);sync();window.addEventListener("hashchange",sync);window.addEventListener("popstate",sync);return()=>{window.removeEventListener("hashchange",sync);window.removeEventListener("popstate",sync)}},[]);
 const tx=publicLabels[locale]||publicLabels.nl;
 const publicItems=[{href:"/"+locale,label:tx[0]},{href:"/"+locale+"/scan",label:tx[1]},{href:"/"+locale+"#features",label:tx[2]},{href:"/"+locale+"#pricing",label:tx[3]},{href:"/"+locale+"/help",label:tx[4]}];
 const ax=appLabels[locale]||appLabels.nl;
 const appItems=[{href:"/dashboard",label:ax[0]},{href:"/dashboard/scan",label:ax[1]},{href:"/dashboard/github",label:ax[2]},{href:"/dashboard/history",label:ax[3]},{href:"/dashboard/more",label:ax[4]}];
 const items=ready&&signedIn?appItems:publicItems; const icons=ready&&signedIn?appIcons:publicIcons;
 const activeIndex=(()=>{const [pathname,hash=""]=locationKey.split("#");if(ready&&signedIn){if(pathname==="/dashboard")return 0;if(pathname?.startsWith("/dashboard/scan"))return 1;if(pathname?.startsWith("/dashboard/github")||pathname?.startsWith("/dashboard/fix"))return 2;if(pathname?.startsWith("/dashboard/history"))return 3;if(pathname?.startsWith("/dashboard/"))return 4;return -1}if(pathname?.includes("/scan"))return 1;if(hash==="features")return 2;if(hash==="pricing")return 3;if(pathname?.endsWith("/help"))return 4;return 0})();
 return <nav className="root-bottom-nav" aria-label="Mobile navigation">{items.map((item,index)=><a href={item.href} key={item.href} onClick={()=>setLocationKey(item.href)} aria-current={activeIndex===index?"page":undefined}><span className="root-bottom-icon"><svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={icons[index]}/></svg></span><span>{item.label}</span></a>)}</nav>
}