import type { Locale } from "./locales";

type Section = { heading: string; paragraphs?: string[]; bullets?: string[]; values?: string[] };
export const aboutContent: Record<Locale, { title: string; sections: Section[] }> = {
  nl: { title: "Over RankFix AI — De Toekomst van Technische SEO en GEO", sections: [
    { heading: "Het verhaal achter RankFix AI", paragraphs: [
      "De digitale wereld is de afgelopen jaren ingrijpend veranderd. Waar online vindbaarheid vroeger volledig draaide om traditionele zoekmachines zoals Google, navigeren consumenten en zakelijke klanten tegenwoordig steeds vaker via kunstmatige intelligentie, ChatGPT, Perplexity en voice-assistenten. Deze verschuiving vraagt om een fundamenteel nieuwe benadering: GEO (Generative Engine Optimization) in combinatie met vlekkeloze technische SEO.",
      "Toch bleef de software om dit speelveld te meten en te optimaliseren achter. Ondernemers, webshop-eigenaren en marketeers werden overspoeld met ondoorzichtige rapporten, eindeloze lijsten met technische foutmeldingen en adviezen waarbij je diep in de code of serverstructuur moest duiken.",
      "Dat kon — en moest — anders. Vanuit die visie is RankFix AI ontwikkeld: een krachtig platform dat complexe data omzet in begrijpelijke taal en directe, veilige acties."
    ] },
    { heading: "Onze Missie: Van Droge Data naar Concrete Actie", paragraphs: [
      "Bij RankFix AI geloven we niet in software die je wel vertelt wat er mis is, maar het opknapwerk aan jou overlaat. Onze missie is simpel: software moet problemen niet alleen signaleren, maar ze ook oplossen.",
      "Wij overbruggen de kloof tussen complexe technische analyses en directe uitvoering. Of het nu gaat om het optimaliseren van je meta-tags, het herstellen van prijsnotaties voor e-commerce, het toevoegen van structured data of het gereedmaken van je website voor AI-zoeksystemen; RankFix AI geeft je de regie in handen."
    ] },
    { heading: "Wat RankFix AI Uniek Maakt", bullets: [
      "Dubbele Kracht (SEO én GEO): We scannen je website niet alleen op klassieke rankingfactoren (zoals laadtijd, H1-structuur en mobiele viewport), maar bereiden je pagina's ook voor op de opkomst van generatieve AI-zoekmachineresultaten.",
      "Diepgaande E-commerce Audits: Webshops hebben unieke uitdagingen. Daarom controleert RankFix AI scherp op conversiegerelateerde en technische factoren zoals correcte prijsnotaties (geen punten i.p.v. komma's), productvarianten, webshop-vertrouwen en Google Ads-readiness.",
      "De Unieke Fix Engine: Geen vage meldingen of losse eindjes. Onze slimme Fix Engine doorloopt een transparante keten (Gevonden → Klaargezet → Wacht op controle → Bevestigd). Zodra een verbetering klaarstaat, activeer je met één klik de AI-ondersteuning om het correct door te voeren.",
      "Geen Onnodige Ballast: Geen zware, trage systemen of ingewikkelde infrastructuren. RankFix AI is ontworpen vanuit een moderne SaaS-filosofie: snel, licht, intuïtief en direct inzetbaar voor zowel zelfstandige ondernemers als marketingbureaus."
    ] },
    { heading: "Onze Kernwaarden", values: [
      "Eerlijkheid & Transparantie: Geen valse beloftes over ‘binnen een week op nummer 1’. Wij leveren een eerlijke, objectieve technische scan die exact laat zien wat er op jouw website gebeurt.",
      "Maximale Efficiëntie: Tijd is kostbaar. Onze tool levert binnen enkele seconden diepgaand inzicht en zorgt ervoor dat technische optimalisaties minimaal tijd en moeite kosten.",
      "Toegankelijkheid: Complexe backend-technologie vertaald naar heldere, menselijke taal. Of je nu een doorgewinterde SEO-specialist bent of net begint met je eerste online shop; RankFix AI werkt voor iedereen."
    ] }
  ] },
  en: { title: "About RankFix AI — The Future of Technical SEO and GEO", sections: [
    { heading: "The story behind RankFix AI", paragraphs: ["Online discovery has changed. Beyond traditional search engines such as Google, customers increasingly use AI, ChatGPT, Perplexity and voice assistants. This shift calls for Generative Engine Optimization (GEO) alongside sound technical SEO.", "Yet the tools used to measure and improve visibility often leave business owners, store operators and marketers with opaque reports, long lists of errors and advice that demands deep technical knowledge.", "RankFix AI was built to turn complex data into clear language and practical, safe actions."] },
    { heading: "Our mission: from data to action", paragraphs: ["Software should do more than point out problems. Our aim is to help solve them.", "RankFix AI connects technical analysis to practical next steps, from meta tags and ecommerce pricing to structured data and readiness for AI search. You remain in control of every change."] },
    { heading: "What makes RankFix AI different", bullets: ["SEO and GEO together: We check established signals such as page speed, heading structure and mobile viewport settings while also looking at signals relevant to AI search.", "Detailed ecommerce audits: We review pricing formats, product variants, trust signals and readiness for Google Ads.", "A transparent fix process: Findings progress from Identified → Prepared → Awaiting review → Confirmed. AI assistance helps prepare a change for your review.", "Built to stay simple: A fast, approachable tool for independent businesses and marketing agencies."] },
    { heading: "Our values", values: ["Honesty and transparency: No promise of a number one ranking. We show what the technical scan actually found.", "Efficiency: Turn findings into clear next steps without unnecessary complexity.", "Accessibility: Make technical findings understandable, whether you are an SEO specialist or opening your first online store."] }
  ] },
  fr: { title: "À propos de RankFix AI — L’avenir du SEO technique et du GEO", sections: [
    { heading: "L’histoire de RankFix AI", paragraphs: ["La découverte en ligne évolue. Au-delà des moteurs classiques comme Google, les clients utilisent de plus en plus l’IA, ChatGPT, Perplexity et les assistants vocaux. Cette évolution appelle une optimisation pour les moteurs génératifs (GEO) associée à un SEO technique solide.", "Pourtant, les outils d’analyse laissent souvent les entreprises, les boutiques en ligne et les spécialistes du marketing face à des rapports obscurs et à des erreurs difficiles à corriger.", "RankFix AI a été conçu pour transformer des données complexes en explications claires et en actions concrètes et sûres."] },
    { heading: "Notre mission : des données à l’action", paragraphs: ["Un logiciel doit faire plus que signaler des problèmes : il doit aider à les résoudre.", "RankFix AI relie l’analyse technique aux prochaines étapes, des balises méta aux prix des produits, en passant par les données structurées et la recherche par IA. Vous gardez le contrôle des modifications."] },
    { heading: "Ce qui distingue RankFix AI", bullets: ["SEO et GEO : nous vérifions la vitesse, les titres et l’affichage mobile ainsi que les signaux utiles à la recherche par IA.", "Audits e-commerce approfondis : formats de prix, variantes de produits, signaux de confiance et préparation pour Google Ads.", "Un parcours de correction transparent : Détecté → Préparé → En attente de vérification → Confirmé. L’IA aide à préparer les modifications que vous vérifiez.", "Une solution simple et rapide pour les entrepreneurs et les agences marketing."] },
    { heading: "Nos valeurs", values: ["Honnêteté et transparence : aucune promesse de première place ; nous présentons les résultats réels de l’analyse.", "Efficacité : des résultats transformés en étapes utiles, sans complexité superflue.", "Accessibilité : des explications claires pour les spécialistes comme pour les nouveaux commerçants."] }
  ] },
  es: { title: "Sobre RankFix AI — El futuro del SEO técnico y el GEO", sections: [
    { heading: "La historia de RankFix AI", paragraphs: ["La forma de encontrar información en internet ha cambiado. Además de Google, los clientes utilizan cada vez más la IA, ChatGPT, Perplexity y los asistentes de voz. Esto exige optimización para motores generativos (GEO) junto con un SEO técnico sólido.", "Sin embargo, muchas herramientas siguen ofreciendo informes opacos, largas listas de errores y consejos que requieren conocimientos técnicos avanzados.", "RankFix AI nació para convertir datos complejos en explicaciones claras y acciones prácticas y seguras."] },
    { heading: "Nuestra misión: de los datos a la acción", paragraphs: ["El software debe hacer más que señalar problemas: debe ayudar a resolverlos.", "RankFix AI conecta el análisis técnico con los siguientes pasos, desde las metaetiquetas y los precios de comercio electrónico hasta los datos estructurados y la búsqueda con IA. Tú decides qué cambios aplicar."] },
    { heading: "Qué distingue a RankFix AI", bullets: ["SEO y GEO: revisamos velocidad, encabezados y visualización móvil, así como señales relevantes para la búsqueda con IA.", "Auditorías de comercio electrónico: formatos de precios, variantes, señales de confianza y preparación para Google Ads.", "Un proceso de mejoras transparente: Detectado → Preparado → Pendiente de revisión → Confirmado. La IA ayuda a preparar los cambios para tu revisión.", "Una herramienta rápida y sencilla para empresas independientes y agencias de marketing."] },
    { heading: "Nuestros valores", values: ["Honestidad y transparencia: no prometemos el primer puesto; mostramos lo que encuentra el análisis técnico.", "Eficiencia: convertimos los resultados en pasos claros sin complejidad innecesaria.", "Accesibilidad: explicaciones comprensibles tanto para especialistas como para quienes abren su primera tienda."] }
  ] },
  it: { title: "Chi è RankFix AI — Il futuro della SEO tecnica e della GEO", sections: [
    { heading: "La storia di RankFix AI", paragraphs: ["Il modo in cui le persone trovano informazioni online è cambiato. Oltre a Google, i clienti usano sempre più l’IA, ChatGPT, Perplexity e gli assistenti vocali. Servono quindi l’ottimizzazione per i motori generativi (GEO) e una solida SEO tecnica.", "Eppure molti strumenti offrono ancora report poco chiari, lunghi elenchi di errori e consigli che richiedono competenze tecniche approfondite.", "RankFix AI nasce per trasformare dati complessi in spiegazioni comprensibili e azioni pratiche e sicure."] },
    { heading: "La nostra missione: dai dati all’azione", paragraphs: ["Il software deve fare più che segnalare problemi: deve aiutare a risolverli.", "RankFix AI collega l’analisi tecnica ai passi successivi, dai meta tag e dai prezzi e-commerce ai dati strutturati e alla ricerca con IA. Ogni modifica resta sotto il tuo controllo."] },
    { heading: "Cosa distingue RankFix AI", bullets: ["SEO e GEO: controlliamo velocità, struttura dei titoli e visualizzazione mobile, oltre ai segnali utili per la ricerca con IA.", "Analisi e-commerce approfondite: formati dei prezzi, varianti, segnali di affidabilità e preparazione per Google Ads.", "Un percorso trasparente: Rilevato → Preparato → In attesa di verifica → Confermato. L’IA aiuta a preparare le modifiche da esaminare.", "Uno strumento rapido e intuitivo per imprese e agenzie di marketing."] },
    { heading: "I nostri valori", values: ["Onestà e trasparenza: nessuna promessa di primo posto; mostriamo ciò che l’analisi tecnica rileva.", "Efficienza: dai risultati a passi concreti senza complessità inutile.", "Accessibilità: spiegazioni chiare per esperti SEO e nuovi titolari di negozi online."] }
  ] },
  de: { title: "Über RankFix AI — Die Zukunft von technischem SEO und GEO", sections: [
    { heading: "Die Geschichte hinter RankFix AI", paragraphs: ["Die Online-Suche hat sich verändert. Neben Google nutzen Kunden zunehmend KI, ChatGPT, Perplexity und Sprachassistenten. Dazu gehören die Optimierung für generative Suchsysteme (GEO) und eine solide technische SEO-Grundlage.", "Viele Werkzeuge liefern jedoch unübersichtliche Berichte, lange Fehlerlisten und Ratschläge, für die tiefes technisches Wissen nötig ist.", "RankFix AI wurde entwickelt, um komplexe Daten in verständliche Erklärungen und konkrete, sichere Schritte zu übersetzen."] },
    { heading: "Unsere Mission: von Daten zu Taten", paragraphs: ["Software sollte Probleme nicht nur melden, sondern bei ihrer Lösung helfen.", "RankFix AI verbindet technische Analysen mit klaren nächsten Schritten: von Meta-Tags und Preisen im Onlineshop bis zu strukturierten Daten und der KI-Suche. Du behältst die Kontrolle über Änderungen."] },
    { heading: "Was RankFix AI auszeichnet", bullets: ["SEO und GEO: Wir prüfen Ladezeit, Überschriften und mobile Darstellung sowie Signale für die KI-Suche.", "Detaillierte Onlineshop-Audits: Preisformate, Produktvarianten, Vertrauenssignale und Vorbereitung auf Google Ads.", "Ein transparenter Ablauf: Erkannt → Vorbereitet → Prüfung ausstehend → Bestätigt. KI hilft bei der Vorbereitung von Änderungen, die du überprüfst.", "Ein schnelles, einfaches Werkzeug für Unternehmen und Marketingagenturen."] },
    { heading: "Unsere Werte", values: ["Ehrlichkeit und Transparenz: keine Versprechen auf Platz eins; wir zeigen die tatsächlichen Ergebnisse des technischen Scans.", "Effizienz: aus Ergebnissen werden klare Schritte ohne unnötige Komplexität.", "Zugänglichkeit: verständliche Erklärungen für SEO-Profis und Menschen mit ihrem ersten Onlineshop."] }
  ] }
};
