import type { Locale } from "./locales";
export const accountCopy: Record<Locale,{login:string;register:string;welcome:string;start:string;startInfo:string;loginInfo:string;name:string;email:string;password:string;confirm:string;remember:string;forgot:string;submitLogin:string;submitRegister:string;busy:string;back:string}> = {
 nl:{login:"Inloggen",register:"Account maken",welcome:"Welkom terug",start:"Start met RankFix AI",startInfo:"Maak gratis een account en start met je eerste audit.",loginInfo:"Log in om je opgeslagen audits te bekijken.",name:"Naam",email:"E-mailadres",password:"Wachtwoord (min. 8 tekens)",confirm:"Herhaal wachtwoord",remember:"Ingelogd blijven",forgot:"Wachtwoord vergeten?",submitLogin:"Inloggen →",submitRegister:"Account aanmaken →",busy:"Even geduld…",back:"Terug naar de website"},
 en:{login:"Log in",register:"Create account",welcome:"Welcome back",start:"Get started with RankFix AI",startInfo:"Create a free account and start your first audit.",loginInfo:"Log in to view your saved audits.",name:"Name",email:"Email address",password:"Password (at least 8 characters)",confirm:"Repeat password",remember:"Keep me signed in",forgot:"Forgot password?",submitLogin:"Log in →",submitRegister:"Create account →",busy:"Please wait…",back:"Back to website"},
 fr:{login:"Connexion",register:"Créer un compte",welcome:"Bon retour",start:"Commencez avec RankFix AI",startInfo:"Créez un compte gratuit et lancez votre premier audit.",loginInfo:"Connectez-vous pour consulter vos audits enregistrés.",name:"Nom",email:"Adresse e-mail",password:"Mot de passe (8 caractères minimum)",confirm:"Confirmez le mot de passe",remember:"Rester connecté",forgot:"Mot de passe oublié ?",submitLogin:"Se connecter →",submitRegister:"Créer un compte →",busy:"Veuillez patienter…",back:"Retour au site"},
 es:{login:"Iniciar sesión",register:"Crear cuenta",welcome:"Bienvenido de nuevo",start:"Empieza con RankFix AI",startInfo:"Crea una cuenta gratis y empieza tu primera auditoría.",loginInfo:"Inicia sesión para ver tus análisis guardados.",name:"Nombre",email:"Correo electrónico",password:"Contraseña (mínimo 8 caracteres)",confirm:"Repite la contraseña",remember:"Mantener sesión",forgot:"¿Olvidaste la contraseña?",submitLogin:"Iniciar sesión →",submitRegister:"Crear cuenta →",busy:"Espera un momento…",back:"Volver al sitio"},
 it:{login:"Accedi",register:"Crea account",welcome:"Bentornato",start:"Inizia con RankFix AI",startInfo:"Crea un account gratuito e avvia il tuo primo audit.",loginInfo:"Accedi per vedere le analisi salvate.",name:"Nome",email:"Indirizzo e-mail",password:"Password (almeno 8 caratteri)",confirm:"Ripeti la password",remember:"Resta connesso",forgot:"Password dimenticata?",submitLogin:"Accedi →",submitRegister:"Crea account →",busy:"Attendi…",back:"Torna al sito"},
 de:{login:"Anmelden",register:"Konto erstellen",welcome:"Willkommen zurück",start:"Starte mit RankFix AI",startInfo:"Erstelle ein kostenloses Konto und starte dein erstes Audit.",loginInfo:"Melde dich an, um gespeicherte Audits zu sehen.",name:"Name",email:"E-Mail-Adresse",password:"Passwort (mindestens 8 Zeichen)",confirm:"Passwort wiederholen",remember:"Angemeldet bleiben",forgot:"Passwort vergessen?",submitLogin:"Anmelden →",submitRegister:"Konto erstellen →",busy:"Bitte warten…",back:"Zurück zur Website"}
};
