import type { Locale } from "./locales";

export const auditCopy: Record<Locale, Record<string, string>> = {
  nl: { back:"Overzicht", loading:"Audit laden…", failed:"Audit laden mislukt.", detail:"AUDITDETAIL", scanned:"Gescand op", newScan:"Nieuwe scan starten", score:"Totaalscore", improvements:"Verbeterpunten", snapshot:"Score van deze scan", issues:"Wat vraagt aandacht?", next:"Volgende stap:", evidence:"Bekijk bewijs", empty:"Deze scan vond geen actieve verbeterpunten.", good:"Wat gaat goed?", passedChecks:"geslaagde controles bekijken", note:"Een codevoorstel verandert je live website pas na publicatie. Voer daarna een nieuwe scan uit om de fix te controleren.", done:"Live bevestigd", waiting:"Codevoorstel · nog niet live bevestigd", pass:"In orde", critical:"Kritiek", important:"Belangrijk", warning:"Aandacht nodig" },
  en: { back:"Overview", loading:"Loading audit…", failed:"Could not load audit.", detail:"AUDIT DETAILS", scanned:"Scanned on", newScan:"Start a new scan", score:"Overall score", improvements:"Improvements", snapshot:"Score from this scan", issues:"What needs attention?", next:"Next step:", evidence:"View evidence", empty:"This scan found no active improvements.", good:"What is working?", passedChecks:"passed checks", note:"A code proposal changes your live website only after publication. Run another scan afterwards to verify the fix.", done:"Verified live", waiting:"Code proposal · not yet verified live", pass:"Passed", critical:"Critical", important:"Important", warning:"Needs attention" },
  fr: { back:"Aperçu", loading:"Chargement de l’audit…", failed:"Impossible de charger l’audit.", detail:"DÉTAIL DE L’AUDIT", scanned:"Analysé le", newScan:"Lancer une analyse", score:"Score global", improvements:"Améliorations", snapshot:"Score de cette analyse", issues:"Que faut-il améliorer ?", next:"Prochaine étape :", evidence:"Voir les preuves", empty:"Cette analyse n’a relevé aucune amélioration en attente.", good:"Qu’est-ce qui fonctionne ?", passedChecks:"contrôles réussis", note:"Une proposition de code ne modifie le site en ligne qu’après publication. Lancez ensuite une nouvelle analyse pour vérifier le correctif.", done:"Vérifié en ligne", waiting:"Proposition de code · non vérifiée en ligne", pass:"Conforme", critical:"Critique", important:"Important", warning:"À surveiller" },
  es: { back:"Resumen", loading:"Cargando análisis…", failed:"No se pudo cargar el análisis.", detail:"DETALLE DEL ANÁLISIS", scanned:"Analizado el", newScan:"Iniciar otro análisis", score:"Puntuación total", improvements:"Mejoras", snapshot:"Puntuación de este análisis", issues:"¿Qué necesita atención?", next:"Siguiente paso:", evidence:"Ver pruebas", empty:"Este análisis no encontró mejoras pendientes.", good:"¿Qué funciona bien?", passedChecks:"comprobaciones correctas", note:"Una propuesta de código solo cambia la web publicada tras aplicarla. Después, realiza otro análisis para verificar la mejora.", done:"Verificado en vivo", waiting:"Propuesta de código · aún sin verificar", pass:"Correcto", critical:"Crítico", important:"Importante", warning:"Necesita atención" },
  it: { back:"Panoramica", loading:"Caricamento analisi…", failed:"Impossibile caricare l’analisi.", detail:"DETTAGLIO ANALISI", scanned:"Analizzato il", newScan:"Avvia una nuova analisi", score:"Punteggio totale", improvements:"Migliorie", snapshot:"Punteggio di questa analisi", issues:"Cosa richiede attenzione?", next:"Passo successivo:", evidence:"Vedi le prove", empty:"Questa analisi non ha trovato migliorie in sospeso.", good:"Cosa funziona?", passedChecks:"controlli superati", note:"Una proposta di codice modifica il sito online solo dopo la pubblicazione. Esegui poi una nuova analisi per verificare la modifica.", done:"Verificato online", waiting:"Proposta di codice · non ancora verificata", pass:"Corretto", critical:"Critico", important:"Importante", warning:"Da controllare" },
  de: { back:"Übersicht", loading:"Audit wird geladen…", failed:"Audit konnte nicht geladen werden.", detail:"AUDITDETAILS", scanned:"Gescannt am", newScan:"Neuen Scan starten", score:"Gesamtscore", improvements:"Verbesserungen", snapshot:"Score dieses Scans", issues:"Was braucht Aufmerksamkeit?", next:"Nächster Schritt:", evidence:"Nachweis ansehen", empty:"Dieser Scan hat keine offenen Verbesserungen gefunden.", good:"Was funktioniert gut?", passedChecks:"bestandene Prüfungen", note:"Ein Codevorschlag ändert deine Live-Website erst nach der Veröffentlichung. Starte danach einen neuen Scan, um die Änderung zu prüfen.", done:"Live bestätigt", waiting:"Codevorschlag · live noch nicht bestätigt", pass:"In Ordnung", critical:"Kritisch", important:"Wichtig", warning:"Handlungsbedarf" }
};
