"use client";
import { useEffect, useState } from "react";
import { languageNames, type Locale } from "@/lib/locales";
import DashboardNav from "../nav";
import "../dashboard.css";
import "./account.css";
const ui: Record<Locale,{title:string;description:string;language:string;save:string;saving:string;saved:string;email:string;security:string;password:string;logout:string;dashboard:string;customerId:string;loadError:string;saveError:string}> = {
 nl:{title:"Accountinstellingen",description:"Beheer je profiel en dashboardtaal.",language:"Dashboardtaal",save:"Taal opslaan",saving:"Opslaan…",saved:"Taal opgeslagen.",email:"E-mailadres",security:"Beveiliging",password:"Wachtwoord opnieuw instellen",logout:"Uitloggen",dashboard:"Dashboard",customerId:"Klant-ID",loadError:"Account laden mislukt.",saveError:"Opslaan mislukt."},
 en:{title:"Account settings",description:"Manage your profile and dashboard language.",language:"Dashboard language",save:"Save language",saving:"Saving…",saved:"Language saved.",email:"Email address",security:"Security",password:"Reset password",logout:"Log out",dashboard:"Dashboard",customerId:"Customer ID",loadError:"Could not load account.",saveError:"Could not save changes."},
 fr:{title:"Paramètres du compte",description:"Gérez votre profil et la langue du tableau de bord.",language:"Langue du tableau de bord",save:"Enregistrer la langue",saving:"Enregistrement…",saved:"Langue enregistrée.",email:"Adresse e-mail",security:"Sécurité",password:"Réinitialiser le mot de passe",logout:"Se déconnecter",dashboard:"Tableau de bord",customerId:"ID client",loadError:"Impossible de charger le compte.",saveError:"Impossible d’enregistrer les modifications."},
 es:{title:"Configuración de cuenta",description:"Gestiona tu perfil y el idioma del panel.",language:"Idioma del panel",save:"Guardar idioma",saving:"Guardando…",saved:"Idioma guardado.",email:"Correo electrónico",security:"Seguridad",password:"Restablecer contraseña",logout:"Cerrar sesión",dashboard:"Panel",customerId:"ID de cliente",loadError:"No se pudo cargar la cuenta.",saveError:"No se pudieron guardar los cambios."},
 it:{title:"Impostazioni account",description:"Gestisci profilo e lingua della dashboard.",language:"Lingua della dashboard",save:"Salva lingua",saving:"Salvataggio…",saved:"Lingua salvata.",email:"Indirizzo e-mail",security:"Sicurezza",password:"Reimposta password",logout:"Esci",dashboard:"Dashboard",customerId:"ID cliente",loadError:"Impossibile caricare l’account.",saveError:"Impossibile salvare le modifiche."},
 de:{title:"Kontoeinstellungen",description:"Verwalte dein Profil und die Dashboard-Sprache.",language:"Dashboard-Sprache",save:"Sprache speichern",saving:"Speichern…",saved:"Sprache gespeichert.",email:"E-Mail-Adresse",security:"Sicherheit",password:"Passwort zurücksetzen",logout:"Abmelden",dashboard:"Dashboard",customerId:"Kunden-ID",loadError:"Konto konnte nicht geladen werden.",saveError:"Änderungen konnten nicht gespeichert werden."}
};
type User = { name:string; email:string; customer_id:string };
export default function AccountSettings() {
 const [user,setUser] = useState<User|null>(null), [language,setLanguage] = useState<Locale>("nl"), [busy,setBusy] = useState(false), [message,setMessage] = useState("");
 const [usage,setUsage]=useState<{plan:string;used:number;limit:number|null;websiteHost:string|null}>({plan:"free",used:0,limit:2,websiteHost:null});
 useEffect(() => { Promise.all([fetch("/api/auth/me").then(r => r.json()),fetch("/api/account/language").then(r => r.ok ? r.json() : null),fetch("/api/history",{cache:"no-store"}).then(r=>r.ok?r.json():null)]).then(([account,preferences,history]) => { if(!account.user){ location.href="/account"; return; } setUser(account.user); if(preferences?.language in ui) setLanguage(preferences.language); if(history?.usage)setUsage(history.usage); }) .catch(() => setMessage(ui[language].loadError)); },[]);
 async function save() { setBusy(true);setMessage("");try { const response=await fetch("/api/account/language",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({language})});if(!response.ok) throw new Error();setMessage(ui[language].saved); }catch{setMessage(ui[language].saveError);}finally{setBusy(false);} }
 async function logout() { await fetch("/api/auth/logout",{method:"POST"});location.href="/"; }
 const t=ui[language];
 return <main className="rf-page" lang={language}><div className="rf-shell"><header className="rf-header"><a href="/" className="rf-brand" aria-label="RankFix AI home">RankFix <span>AI</span></a><a href="/dashboard" className="rf-back">← {t.dashboard}</a></header><DashboardNav current={6}/><div className="rf-body"><div className="rf-heading"><h1>{t.title}</h1><p>{t.description}</p></div><div className="rf-account-grid"><section className="rf-card"><span className="rf-eyebrow">{language==="nl"?"Abonnement":language==="de"?"Abo":language==="fr"?"Abonnement":language==="it"?"Abbonamento":language==="es"?"Plan":"Plan"}</span><h2>{usage.plan==="free"?"Free · €0":usage.plan}</h2><p>{usage.limit!==null?`${usage.used} / ${usage.limit} ${language==="nl"?"scans deze maand":language==="de"?"Scans diesen Monat":language==="fr"?"analyses ce mois-ci":language==="it"?"scansioni questo mese":language==="es"?"análisis este mes":"scans this month"}`:"—"}</p>{usage.plan==="free"&&<><p>{language==="nl"?"AI-fixes: niet inbegrepen":language==="de"?"AI-Fixes: nicht enthalten":language==="fr"?"Correctifs IA : non inclus":language==="it"?"Correzioni AI: non incluse":language==="es"?"Correcciones de IA: no incluidas":"AI fixes: not included"}</p><a href="/#pricing">{language==="nl"?"Bekijk abonnementen":language==="de"?"Tarife ansehen":language==="fr"?"Voir les offres":language==="it"?"Vedi i piani":language==="es"?"Ver planes":"View plans"} →</a></>}</section><section className="rf-card"><h2>{user?.name || "…"}</h2><p>{t.email}: {user?.email || "—"}</p><p>{t.customerId}: <strong>{user?.customer_id || "—"}</strong></p></section><section className="rf-card"><label htmlFor="dashboard-language">{t.language}</label><select id="dashboard-language" value={language} onChange={e => setLanguage(e.target.value as Locale)}>{Object.entries(languageNames).map(([code,name]) => <option key={code} value={code}>{name}</option>)}</select><button onClick={save} disabled={busy}>{busy ? t.saving : t.save}</button>{message && <p role="status">{message}</p>}</section><section className="rf-card"><h2>{t.security}</h2><a href={`/account/forgot-password?lang=${language}`}>{t.password} →</a><button onClick={logout}>{t.logout}</button></section></div></div></div></main>;
}
