"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { languageNames, type Locale } from "@/lib/locales";
import DashboardNav from "../nav";
import "../dashboard.css";
import "./account.css";
const ui: Record<Locale,{title:string;description:string;language:string;save:string;saving:string;saved:string;email:string;security:string;password:string;logout:string;dashboard:string;customerId:string;loadError:string;saveError:string;subscription:string;scansMonth:string;aiFixes:string;notIncluded:string;viewPlans:string;resets:string;website:string}> = {
 nl:{title:"Accountinstellingen",description:"Beheer je profiel en dashboardtaal.",language:"Dashboardtaal",save:"Taal opslaan",saving:"Opslaan…",saved:"Taal opgeslagen.",email:"E-mailadres",security:"Beveiliging",password:"Wachtwoord opnieuw instellen",logout:"Uitloggen",dashboard:"Dashboard",customerId:"Klant-ID",loadError:"Account laden mislukt.",saveError:"Opslaan mislukt.",subscription:"Abonnement",scansMonth:"scans deze maand",aiFixes:"AI-fixes",notIncluded:"niet inbegrepen",viewPlans:"Bekijk abonnementen",resets:"Nieuwe maandlimiet vanaf",website:"Website"},
 en:{title:"Account settings",description:"Manage your profile and dashboard language.",language:"Dashboard language",save:"Save language",saving:"Saving…",saved:"Language saved.",email:"Email address",security:"Security",password:"Reset password",logout:"Log out",dashboard:"Dashboard",customerId:"Customer ID",loadError:"Could not load account.",saveError:"Could not save changes.",subscription:"Plan",scansMonth:"scans this month",aiFixes:"AI fixes",notIncluded:"not included",viewPlans:"View plans",resets:"Monthly limit resets",website:"Website"},
 fr:{title:"Paramètres du compte",description:"Gérez votre profil et la langue du tableau de bord.",language:"Langue du tableau de bord",save:"Enregistrer la langue",saving:"Enregistrement…",saved:"Langue enregistrée.",email:"Adresse e-mail",security:"Sécurité",password:"Réinitialiser le mot de passe",logout:"Se déconnecter",dashboard:"Tableau de bord",customerId:"ID client",loadError:"Impossible de charger le compte.",saveError:"Impossible d’enregistrer les modifications.",subscription:"Abonnement",scansMonth:"analyses ce mois-ci",aiFixes:"Correctifs IA",notIncluded:"non inclus",viewPlans:"Voir les offres",resets:"Nouvelle limite mensuelle à partir du",website:"Site"},
 es:{title:"Configuración de cuenta",description:"Gestiona tu perfil y el idioma del panel.",language:"Idioma del panel",save:"Guardar idioma",saving:"Guardando…",saved:"Idioma guardado.",email:"Correo electrónico",security:"Seguridad",password:"Restablecer contraseña",logout:"Cerrar sesión",dashboard:"Panel",customerId:"ID de cliente",loadError:"No se pudo cargar la cuenta.",saveError:"No se pudieron guardar los cambios.",subscription:"Plan",scansMonth:"análisis este mes",aiFixes:"Correcciones de IA",notIncluded:"no incluidas",viewPlans:"Ver planes",resets:"Nuevo límite mensual desde",website:"Sitio"},
 it:{title:"Impostazioni account",description:"Gestisci profilo e lingua della dashboard.",language:"Lingua della dashboard",save:"Salva lingua",saving:"Salvataggio…",saved:"Lingua salvata.",email:"Indirizzo e-mail",security:"Sicurezza",password:"Reimposta password",logout:"Esci",dashboard:"Dashboard",customerId:"ID cliente",loadError:"Impossibile caricare l’account.",saveError:"Impossibile salvare le modifiche.",subscription:"Abbonamento",scansMonth:"scansioni questo mese",aiFixes:"Correzioni AI",notIncluded:"non incluse",viewPlans:"Vedi i piani",resets:"Nuovo limite mensile dal",website:"Sito"},
 de:{title:"Kontoeinstellungen",description:"Verwalte dein Profil und die Dashboard-Sprache.",language:"Dashboard-Sprache",save:"Sprache speichern",saving:"Speichern…",saved:"Sprache gespeichert.",email:"E-Mail-Adresse",security:"Sicherheit",password:"Passwort zurücksetzen",logout:"Abmelden",dashboard:"Dashboard",customerId:"Kunden-ID",loadError:"Konto konnte nicht geladen werden.",saveError:"Änderungen konnten nicht gespeichert werden.",subscription:"Abo",scansMonth:"Scans diesen Monat",aiFixes:"AI-Fixes",notIncluded:"nicht enthalten",viewPlans:"Tarife ansehen",resets:"Neues Monatslimit ab",website:"Website"}
};
type User = { name:string; email:string; customer_id:string };
export default function AccountSettings() {
 const router=useRouter();
 const [user,setUser] = useState<User|null>(null), [language,setLanguage] = useState<Locale>("nl"), [busy,setBusy] = useState(false), [message,setMessage] = useState("");
 const [usage,setUsage]=useState<{plan:string;used:number;limit:number|null;websiteHost:string|null}>({plan:"free",used:0,limit:2,websiteHost:null});
 useEffect(() => { Promise.all([fetch("/api/auth/me").then(r => r.json()),fetch("/api/account/language").then(r => r.ok ? r.json() : null),fetch("/api/history",{cache:"no-store"}).then(r=>r.ok?r.json():null)]).then(([account,preferences,history]) => { if(!account.user){ router.push("/account"); return; } setUser(account.user); if(preferences?.language in ui) setLanguage(preferences.language); if(history?.usage)setUsage(history.usage); }) .catch(() => setMessage(ui[language].loadError)); },[]);
 async function save() { setBusy(true);setMessage("");try { const response=await fetch("/api/account/language",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({language})});if(!response.ok) throw new Error();setMessage(ui[language].saved); }catch{setMessage(ui[language].saveError);}finally{setBusy(false);} }
 async function logout() { await fetch("/api/auth/logout",{method:"POST"});router.push("/"); }
 const t=ui[language];
 const planName=usage.plan==="free"?"Free · €0":usage.plan.charAt(0).toUpperCase()+usage.plan.slice(1);
 const resetDate=new Intl.DateTimeFormat(language==="nl"?"nl-NL":language==="de"?"de-DE":language==="fr"?"fr-FR":language==="it"?"it-IT":language==="es"?"es-ES":"en-GB",{day:"numeric",month:"long",timeZone:"UTC"}).format(new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth()+1,1)));
 return <main className="rf-page" lang={language}><div className="rf-shell"><header className="rf-header"><Link href="/" className="rf-brand" aria-label="RankFix AI home">RankFix <span>AI</span></Link><Link href="/dashboard" className="rf-back">← {t.dashboard}</Link></header><DashboardNav current={6}/><div className="rf-body"><Link href="/dashboard" className="rf-page-back">← {language==="nl"?"Terug naar Overzicht":language==="de"?"Zurück zur Übersicht":language==="fr"?"Retour à l’aperçu":language==="it"?"Torna alla panoramica":language==="es"?"Volver al resumen":"Back to Overview"}</Link><div className="rf-heading"><h1>{t.title}</h1><p>{t.description}</p></div><div className="rf-account-grid"><section className="rf-card"><span className="rf-eyebrow">{t.subscription}</span><h2>{planName}</h2><p>{usage.limit!==null?`${usage.used} / ${usage.limit} ${t.scansMonth}`:"—"}</p>{usage.websiteHost&&<p>{t.website}: <strong>{usage.websiteHost}</strong></p>}{usage.plan==="free"&&<><p>{t.aiFixes}: {t.notIncluded}</p><p>{t.resets}: <strong>{resetDate}</strong></p><Link href={`/${language}#pricing`}>{t.viewPlans} →</Link></>}</section><section className="rf-card"><h2>{user?.name || "…"}</h2><p>{t.email}: {user?.email || "—"}</p><p>{t.customerId}: <strong>{user?.customer_id || "—"}</strong></p></section><section className="rf-card"><label htmlFor="dashboard-language">{t.language}</label><select id="dashboard-language" value={language} onChange={e => setLanguage(e.target.value as Locale)}>{Object.entries(languageNames).map(([code,name]) => <option key={code} value={code}>{name}</option>)}</select><button onClick={save} disabled={busy}>{busy ? t.saving : t.save}</button>{message && <p role="status">{message}</p>}</section><section className="rf-card"><h2>{t.security}</h2><Link href={`/account/forgot-password?lang=${language}`}>{t.password} →</Link><button onClick={logout}>{t.logout}</button></section></div></div></div></main>;
}
