import { notFound } from "next/navigation";
import { copy, isLocale, locales } from "@/lib/locales";
import { localeMetadata } from "@/lib/locale-metadata";
import LocaleShell from "./shell";
export function generateStaticParams() { return locales.map(locale => ({ locale })); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; return isLocale(locale) ? localeMetadata(locale) : {}; }
export default async function LocalizedHome({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound();
  const t = copy[locale];
  return <LocaleShell locale={locale}>
    <section className="lc-container lc-hero"><p className="lc-kicker">SEO · GEO · RankFix AI</p><h1>{t.hero}</h1><p className="lc-lead">{t.intro}</p><div className="lc-actions"><a className="lc-primary" href={"/" + locale + "/scan"}>{t.scan} →</a><a className="lc-secondary" href={"#" + "how"}>{t.nav[1]}</a></div></section>
    <section className="lc-section" id="how"><div className="lc-container"><h2>{t.processTitle}</h2><div className="lc-grid">{t.steps.map((step, index) => <div className="lc-card" key={index}><strong>0{index + 1}</strong>{step}</div>)}</div></div></section>
    <section className="lc-section" id="features"><div className="lc-container"><p className="lc-kicker">{locale==="nl"?"Van inzicht naar verbetering":locale==="en"?"From insight to improvement":locale==="de"?"Von Erkenntnis zur Verbesserung":locale==="fr"?"De l’analyse à l’amélioration":locale==="it"?"Dall’analisi al miglioramento":"Del análisis a la mejora"}</p><h2>{locale==="nl"?"Van scan naar actie.":locale==="en"?"From scan to action.":locale==="de"?"Vom Scan zur Umsetzung.":locale==="fr"?"Du scan à l’action.":locale==="it"?"Dalla scansione all’azione.":"Del escaneo a la acción."}</h2><div className="lc-grid lc-feature-grid">{[
      ["SEO + GEO audit",locale==="nl"?"Technische SEO, metadata, structured data, entities, social metadata, URL-hygiëne en AI-search signalen.":locale==="en"?"Technical SEO, metadata, structured data, entities, social metadata, URL hygiene and AI-search signals.":locale==="de"?"Technisches SEO, Metadaten, strukturierte Daten, Entitäten, Social Metadata, URL-Hygiene und AI-Search-Signale.":locale==="fr"?"SEO technique, métadonnées, données structurées, entités, métadonnées sociales, hygiène des URL et signaux AI Search.":locale==="it"?"SEO tecnico, metadati, dati strutturati, entità, social metadata, igiene URL e segnali AI Search.":"SEO técnico, metadatos, datos estructurados, entidades, metadatos sociales, higiene de URL y señales de AI Search."],
      [locale==="nl"?"Webshop audit":locale==="en"?"Online store audit":locale==="de"?"Onlineshop-Audit":locale==="fr"?"Audit e-commerce":locale==="it"?"Audit e-commerce":"Auditoría e-commerce",locale==="nl"?"Product-schema, prijsnotatie, retour- en verzendsignalen, reviewplatforms, checkout-trust en variant-URL's.":locale==="en"?"Product schema, pricing, return and shipping signals, review platforms, checkout trust and variant URLs.":locale==="de"?"Produktschema, Preisangaben, Rückgabe- und Versandsignale, Bewertungsplattformen, Checkout-Vertrauen und Varianten-URLs.":locale==="fr"?"Schéma produit, prix, retours et livraison, plateformes d’avis, confiance au checkout et URL de variantes.":locale==="it"?"Schema prodotto, prezzi, resi e spedizioni, piattaforme recensioni, fiducia nel checkout e URL varianti.":"Esquema de producto, precios, devoluciones y envíos, plataformas de reseñas, confianza en checkout y URL de variantes."],
      ["Ads readiness",locale==="nl"?"Controle van landingspagina, tracking-signalen, GA4/GTM en Google Ads-conversies.":locale==="en"?"Checks landing pages, tracking signals, GA4/GTM and Google Ads conversions.":locale==="de"?"Prüft Landingpages, Tracking-Signale, GA4/GTM und Google-Ads-Conversions.":locale==="fr"?"Contrôle les pages d’atterrissage, signaux de suivi, GA4/GTM et conversions Google Ads.":locale==="it"?"Controlla landing page, segnali di tracking, GA4/GTM e conversioni Google Ads.":"Comprueba landing pages, señales de seguimiento, GA4/GTM y conversiones de Google Ads."],
      ["Fix Engine",locale==="nl"?"Concrete verbeteringen en veilige codevoorstellen. Publiceer eerst en bevestig daarna met een nieuwe live scan.":locale==="en"?"Concrete improvements and safe code proposals. Publish first, then confirm with a new live scan.":locale==="de"?"Konkrete Verbesserungen und sichere Codevorschläge. Erst veröffentlichen, dann mit einem neuen Live-Scan bestätigen.":locale==="fr"?"Améliorations concrètes et propositions de code sûres. Publiez puis confirmez avec un nouveau scan en direct.":locale==="it"?"Miglioramenti concreti e proposte di codice sicure. Pubblica e poi conferma con una nuova scansione live.":"Mejoras concretas y propuestas de código seguras. Publica y confirma después con un nuevo escaneo en vivo."]
    ].map(([title,text],index)=><div className="lc-card" key={title}><strong>0{index+1}</strong><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="lc-section lc-honest-fixes"><div className="lc-container"><p className="lc-kicker">{locale==="nl"?"Eerlijke fixes":locale==="en"?"Honest fixes":locale==="de"?"Ehrliche Fixes":locale==="fr"?"Correctifs transparents":locale==="it"?"Correzioni trasparenti":"Mejoras transparentes"}</p><h2>{locale==="nl"?'Geen “fix klaar” als er niets is veranderd.':locale==="en"?'No “fix complete” when nothing has changed.':locale==="de"?'Kein „Fix erledigt“, wenn sich nichts geändert hat.':locale==="fr"?'Pas de « correction terminée » si rien n’a changé.':locale==="it"?'Nessun “fix completato” se non è cambiato nulla.':'Nada de “mejora completada” si nada ha cambiado.'}</h2><p className="lc-lead">{locale==="nl"?"Elke technische fix doorloopt dezelfde keten: gevonden → gecontroleerd → echt gewijzigd → opnieuw gecontroleerd.":locale==="en"?"Every technical fix follows the same chain: found → reviewed → actually changed → checked again.":locale==="de"?"Jeder technische Fix durchläuft dieselbe Kette: gefunden → geprüft → wirklich geändert → erneut geprüft.":locale==="fr"?"Chaque correction technique suit la même chaîne : détectée → vérifiée → réellement modifiée → vérifiée à nouveau.":locale==="it"?"Ogni correzione tecnica segue la stessa catena: trovata → verificata → realmente modificata → verificata di nuovo.":"Cada mejora técnica sigue la misma cadena: encontrada → revisada → realmente modificada → revisada de nuevo."}</p><div className="lc-grid lc-fix-grid">{[
      ["🟠",locale==="nl"?"Gevonden":locale==="en"?"Found":locale==="de"?"Gefunden":locale==="fr"?"Détecté":locale==="it"?"Trovato":"Encontrado",locale==="nl"?"RankFix legt in gewone taal uit wat er misgaat en waarom het telt.":locale==="en"?"RankFix explains in plain language what is wrong and why it matters.":locale==="de"?"RankFix erklärt verständlich, was falsch ist und warum es wichtig ist.":locale==="fr"?"RankFix explique clairement ce qui ne va pas et pourquoi c’est important.":locale==="it"?"RankFix spiega in modo semplice cosa non va e perché è importante.":"RankFix explica claramente qué falla y por qué importa."],
      ["🔵",locale==="nl"?"Codevoorstel":locale==="en"?"Code proposal":locale==="de"?"Codevorschlag":locale==="fr"?"Proposition de code":locale==="it"?"Proposta di codice":"Propuesta de código",locale==="nl"?"De wijziging staat in een aparte pull request, nog niet op de live website.":locale==="en"?"The change is in a separate pull request, not yet on the live website.":locale==="de"?"Die Änderung befindet sich in einem separaten Pull Request, noch nicht auf der Live-Website.":locale==="fr"?"La modification se trouve dans une pull request séparée, pas encore sur le site en ligne.":locale==="it"?"La modifica è in una pull request separata, non ancora sul sito live.":"El cambio está en una pull request separada, aún no en el sitio en vivo."],
      ["🟡",locale==="nl"?"Nog te bevestigen":locale==="en"?"Pending confirmation":locale==="de"?"Noch zu bestätigen":locale==="fr"?"À confirmer":locale==="it"?"Da confermare":"Pendiente de confirmar",locale==="nl"?"Publiceer de codewijziging en scan de live website opnieuw.":locale==="en"?"Publish the code change and scan the live website again.":locale==="de"?"Veröffentliche die Codeänderung und scanne die Live-Website erneut.":locale==="fr"?"Publiez la modification du code puis analysez à nouveau le site en ligne.":locale==="it"?"Pubblica la modifica del codice e scansiona nuovamente il sito live.":"Publica el cambio de código y vuelve a escanear el sitio en vivo."],
      ["🟢",locale==="nl"?"Bevestigd":locale==="en"?"Confirmed":locale==="de"?"Bestätigt":locale==="fr"?"Confirmé":locale==="it"?"Confermato":"Confirmado",locale==="nl"?"De live scan laat zien dat de verbetering daadwerkelijk aanwezig is.":locale==="en"?"The live scan shows that the improvement is actually present.":locale==="de"?"Der Live-Scan zeigt, dass die Verbesserung tatsächlich vorhanden ist.":locale==="fr"?"Le scan en direct montre que l’amélioration est réellement présente.":locale==="it"?"La scansione live mostra che il miglioramento è effettivamente presente.":"El escaneo en vivo muestra que la mejora está realmente presente."]
    ].map(([icon,title,text])=><div className="lc-card lc-fix-card" key={title}><div className="lc-fix-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="lc-section" id="pricing"><div className="lc-container"><h2>{t.pricingTitle}</h2><p className="lc-lead">{t.pricing}</p><div className="lc-grid lc-pricing-grid" style={{marginTop:24}}>{[
      ["FREE","€0",["1 website","1 volledige audit","SEO + GEO basis","Actiepunten","Geen AI-fix"]],
      ["START","€29",["1 website","10 scans / maand","10 AI-fixcredits","SEO + GEO audit","3 maanden scanhistorie"]],
      ["BUSINESS","€59",["5 websites","30 scans / maand","30 AI-fixcredits","Automatische controles","PDF- en e-mailrapporten"]],
      ["E-COMMERCE","€79",["5 webshops","50 scans / maand","50 AI-fixcredits","Shopify, WooCommerce & Next.js/custom","Product-, categorie- en structured-data checks"]],
      ["PRO","€89",["15 websites","100 scans / maand","80 AI-fixcredits","Uitgebreide automatisering","Tot 5 gebruikers"]],
      ["AGENCY","€179",["50 websites","300 scans / maand","200 AI-fixcredits","White-label rapporten","API + team/workflow"]]
    ].map(([name,price,items])=><div className="lc-card lc-price-card" key={name as string}><strong>{name as string}</strong><div className="lc-price">{price as string}{price!=="€0"&&<small> / maand</small>}</div><ul>{(items as string[]).map(item=><li key={item}>✓ {item}</li>)}</ul><div className="lc-coming-soon">{locale==="nl"?"Binnenkort beschikbaar":locale==="en"?"Coming soon":locale==="de"?"Bald verfügbar":locale==="fr"?"Bientôt disponible":locale==="it"?"Prossimamente":"Próximamente"}</div></div>)}</div><div className="lc-actions" style={{marginTop:24}}><a className="lc-primary" href={"/" + locale + "/scan"}>{t.nav[0]}</a></div></div></section>
    <section className="lc-section" id="audience"><div className="lc-container"><h2>{t.audienceTitle}</h2><div className="lc-grid">{t.audiences.map((item, index) => <div className="lc-card" key={index}>{item}</div>)}</div></div></section>
    <section className="lc-section" id="contact"><div className="lc-container"><h2>{t.nav[4]}</h2><p className="lc-lead">{t.contact}</p><div className="lc-actions"><a className="lc-primary" href={"/" + locale + "/contact"}>{t.nav[4]} →</a></div></div></section>
  </LocaleShell>;
}
