import { notFound } from "next/navigation";
import { copy, isLocale, locales } from "@/lib/locales";
import { localeMetadata } from "@/lib/locale-metadata";
import LocaleShell from "./shell";
export function generateStaticParams() { return locales.map(locale => ({ locale })); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; return isLocale(locale) ? localeMetadata(locale) : {}; }
export default async function LocalizedHome({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound();
  const t = copy[locale];
  return <LocaleShell locale={locale}>
    <section className="lc-container lc-hero"><p className="lc-kicker">SEO · GEO · RankFix AI</p><h1>{t.hero}</h1><p className="lc-lead">{t.intro}</p><div className="lc-actions"><a className="lc-primary" href={"/" + locale + "/scan"}>{t.scan} →</a><a className="lc-secondary" href={"#" + "how"}>{t.nav[1]}</a></div></section>
    <section className="lc-section" id="how"><div className="lc-container"><h2>{t.processTitle}</h2><div className="lc-grid">{t.steps.map((step, index) => <div className="lc-card" key={index}><strong>0{index + 1}</strong>{step}</div>)}</div></div></section>
    <section className="lc-section" id="features"><div className="lc-container"><p className="lc-kicker">{locale==="nl"?"Van inzicht naar verbetering":locale==="en"?"From insight to improvement":locale==="de"?"Von Erkenntnis zur Verbesserung":locale==="fr"?"De l’analyse à l’amélioration":locale==="it"?"Dall’analisi al miglioramento":"Del análisis a la mejora"}</p><h2>{locale==="nl"?"Van scan naar actie.":locale==="en"?"From scan to action.":locale==="de"?"Vom Scan zur Umsetzung.":locale==="fr"?"Du scan à l’action.":locale==="it"?"Dalla scansione all’azione.":"Del escaneo a la acción."}</h2><div className="lc-grid lc-feature-grid">{[
      ["SEO + GEO audit",locale==="nl"?"Technische SEO, metadata, structured data, entities, social metadata, URL-hygiëne en AI-search signalen.":locale==="en"?"Technical SEO, metadata, structured data, entities, social metadata, URL hygiene and AI-search signals.":locale==="de"?"Technisches SEO, Metadaten, strukturierte Daten, Entitäten, Social Metadata, URL-Hygiene und AI-Search-Signale.":locale==="fr"?"SEO technique, métadonnées, données structurées, entités, métadonnées sociales, hygiène des URL et signaux AI Search.":locale==="it"?"SEO tecnico, metadati, dati strutturati, entità, social metadata, igiene URL e segnali AI Search.":"SEO técnico, metadatos, datos estructurados, entidades, metadatos sociales, higiene de URL y señales de AI Search."],
      [locale==="nl"?"Webshop audit":locale==="en"?"Online store audit":locale==="de"?"Onlineshop-Audit":locale==="fr"?"Audit e-commerce":locale==="it"?"Audit e-commerce":"Auditoría e-commerce",locale==="nl"?"Product-schema, prijsnotatie, retour- en verzendsignalen, reviewplatforms, checkout-trust en variant-URL's.":locale==="en"?"Product schema, pricing, return and shipping signals, review platforms, checkout trust and variant URLs.":locale==="de"?"Produktschema, Preisangaben, Rückgabe- und Versandsignale, Bewertungsplattformen, Checkout-Vertrauen und Varianten-URLs.":locale==="fr"?"Schéma produit, prix, retours et livraison, plateformes d’avis, confiance au checkout et URL de variantes.":locale==="it"?"Schema prodotto, prezzi, resi e spedizioni, piattaforme recensioni, fiducia nel checkout e URL varianti.":"Esquema de producto, precios, devoluciones y envíos, plataformas de reseñas, confianza en checkout y URL de variantes."],
      ["Ads readiness",locale==="nl"?"Controle van landingspagina, tracking-signalen, GA4/GTM en Google Ads-conversies.":locale==="en"?"Checks landing pages, tracking signals, GA4/GTM and Google Ads conversions.":locale==="de"?"Prüft Landingpages, Tracking-Signale, GA4/GTM und Google-Ads-Conversions.":locale==="fr"?"Contrôle les pages d’atterrissage, signaux de suivi, GA4/GTM et conversions Google Ads.":locale==="it"?"Controlla landing page, segnali di tracking, GA4/GTM e conversioni Google Ads.":"Comprueba landing pages, señales de seguimiento, GA4/GTM y conversiones de Google Ads."],
      ["Fix Engine",locale==="nl"?"Concrete verbeteringen en veilige codevoorstellen. Publiceer eerst en bevestig daarna met een nieuwe live scan.":locale==="en"?"Concrete improvements and safe code proposals. Publish first, then confirm with a new live scan.":locale==="de"?"Konkrete Verbesserungen und sichere Codevorschläge. Erst veröffentlichen, dann mit einem neuen Live-Scan bestätigen.":locale==="fr"?"Améliorations concrètes et propositions de code sûres. Publiez puis confirmez avec un nouveau scan en direct.":locale==="it"?"Miglioramenti concreti e proposte di codice sicure. Pubblica e poi conferma con una nuova scansione live.":"Mejoras concretas y propuestas de código seguras. Publica y confirma después con un nuevo escaneo en vivo."]
    ].map(([title,text],index)=><div className="lc-card" key={title}><strong>0{index+1}</strong><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="lc-section" id="pricing"><div className="lc-container"><h2>{t.pricingTitle}</h2><p className="lc-lead">{t.pricing}</p><div className="lc-grid" style={{marginTop:24}}>{[["FREE","€0"],["START","€29"],["BUSINESS","€59"],["E-COMMERCE","€79"],["PRO","€89"],["AGENCY","€179"]].map(([name,price])=><div className="lc-card" key={name}><strong>{name}</strong><div style={{fontSize:24,fontWeight:800,marginTop:8}}>{price}{price!=="€0"&&<small style={{fontSize:12,fontWeight:500}}> / maand</small>}</div></div>)}</div><div className="lc-actions" style={{marginTop:24}}><a className="lc-primary" href={"/" + locale + "/scan"}>{t.nav[0]}</a></div></div></section>
    <section className="lc-section" id="audience"><div className="lc-container"><h2>{t.audienceTitle}</h2><div className="lc-grid">{t.audiences.map((item, index) => <div className="lc-card" key={index}>{item}</div>)}</div></div></section>
    <section className="lc-section" id="contact"><div className="lc-container"><h2>{t.nav[4]}</h2><p className="lc-lead">{t.contact}</p><div className="lc-actions"><a className="lc-primary" href={"/" + locale + "/contact"}>{t.nav[4]} →</a></div></div></section>
  </LocaleShell>;
}
