import { copy, type Locale } from "@/lib/locales";
import PublicHeader from "./public-header";
import MobileNav from "./mobile-nav";
import AiAssistant from "@/components/ai-assistant";
import "./locale.css";
export default function LocaleShell({ locale, page = "", children }: { locale: Locale; page?: string; children: React.ReactNode }) {
  const t = copy[locale];
  return <main className="lc-page" lang={locale}>
    <PublicHeader locale={locale} page={page} />\n    {children}
    <footer className="lc-footer">
      <div className="lc-container lc-footer-grid">
        <div className="lc-footer-brand"><div className="lc-footer-logo"><span>RF</span><strong>RankFix</strong></div><p>{locale==="nl"?"RankFix controleert websites en webshops op SEO, GEO, techniek en online vindbaarheid. Je krijgt duidelijke verbeterpunten, hulp bij het oplossen en een herscan om het resultaat te controleren.":locale==="en"?"RankFix checks websites and online stores for SEO, GEO, technical quality and search visibility. Get clear improvements, guided fixes and a rescan to verify the result.":locale==="de"?"RankFix prüft Websites und Onlineshops auf SEO, GEO, Technik und Sichtbarkeit. Du erhältst klare Verbesserungen, Hilfe bei der Behebung und einen erneuten Scan zur Kontrolle.":locale==="fr"?"RankFix contrôle les sites et boutiques en ligne pour le SEO, le GEO, la technique et la visibilité. Obtenez des améliorations claires, une aide à la correction et une nouvelle analyse pour vérifier le résultat.":locale==="it"?"RankFix controlla siti e negozi online per SEO, GEO, qualità tecnica e visibilità. Ricevi miglioramenti chiari, assistenza nelle correzioni e una nuova scansione per verificarne il risultato.":"RankFix revisa sitios y tiendas online para SEO, GEO, calidad técnica y visibilidad. Recibe mejoras claras, ayuda para corregirlas y un nuevo análisis para verificar el resultado."}</p></div>
        <div><strong>{locale==="nl"?"RankFix":locale==="en"?"RankFix":locale==="de"?"RankFix":locale==="fr"?"RankFix":locale==="it"?"RankFix":"RankFix"}</strong><div className="lc-footer-column"><a href={"/"+locale+"/scan"}>{locale==="nl"?"Website scan":locale==="en"?"Website scan":locale==="de"?"Website-Scan":locale==="fr"?"Analyse du site":locale==="it"?"Scansione sito":"Análisis del sitio"}</a><a href={"/"+locale+"#how"}>{locale==="nl"?"Problemen oplossen":locale==="en"?"Fix improvements":locale==="de"?"Probleme beheben":locale==="fr"?"Corriger les problèmes":locale==="it"?"Risolvi i problemi":"Resolver problemas"}</a><a href={"/"+locale+"#features"}>{locale==="nl"?"SEO & GEO":locale==="en"?"SEO & GEO":locale==="de"?"SEO & GEO":locale==="fr"?"SEO & GEO":locale==="it"?"SEO & GEO":"SEO & GEO"}</a><a href={"/"+locale+"#features"}>{locale==="nl"?"Webshop controle":locale==="en"?"Online store checks":locale==="de"?"Onlineshop-Prüfung":locale==="fr"?"Contrôle e-commerce":locale==="it"?"Controllo e-commerce":"Control de tienda online"}</a></div></div>
        <div><strong>{locale==="nl"?"Voor wie":locale==="en"?"For whom":locale==="de"?"Für wen":locale==="fr"?"Pour qui":locale==="it"?"Per chi":"Para quién"}</strong><div className="lc-footer-column"><a href={"/"+locale+"#audience"}>{locale==="nl"?"Bedrijven":locale==="en"?"Businesses":locale==="de"?"Unternehmen":locale==="fr"?"Entreprises":locale==="it"?"Aziende":"Empresas"}</a><a href={"/"+locale+"#audience"}>{locale==="nl"?"Webshops":locale==="en"?"Online stores":locale==="de"?"Onlineshops":locale==="fr"?"Boutiques en ligne":locale==="it"?"Negozi online":"Tiendas online"}</a><a href={"/"+locale+"#audience"}>{locale==="nl"?"Agencies":locale==="en"?"Agencies":locale==="de"?"Agenturen":locale==="fr"?"Agences":locale==="it"?"Agenzie":"Agencias"}</a><a href={"/"+locale+"#audience"}>SaaS</a></div></div>
        <div><strong>{locale==="nl"?"Bedrijf":locale==="en"?"Company":locale==="de"?"Unternehmen":locale==="fr"?"Entreprise":locale==="it"?"Azienda":"Empresa"}</strong><div className="lc-footer-column"><a href={"/"+locale+"/about"}>{t.aboutTitle}</a><a href={"/"+locale+"#contact"}>{locale==="nl"?"Contact":locale==="de"?"Kontakt":locale==="it"?"Contatti":"Contact"}</a><a href={"/"+locale+"/privacy"}>{t.privacyTitle}</a><a href={"/"+locale+"/terms"}>{t.termsTitle}</a><a href={"/"+locale+"/cookies"}>{t.cookiesTitle}</a></div></div>
      </div>
      <div className="lc-container lc-footer-bottom"><span>© 2026 RankFix. {locale==="nl"?"Alle rechten voorbehouden.":locale==="en"?"All rights reserved.":locale==="de"?"Alle Rechte vorbehalten.":locale==="fr"?"Tous droits réservés.":locale==="it"?"Tutti i diritti riservati.":"Todos los derechos reservados."}</span><span>SEO · GEO · Techniek · Webshops · Controle na fixes</span></div>
    </footer>
    <AiAssistant publicLocale={locale} />
    <MobileNav locale={locale} page={page} />
  </main>;
}
