"use client";
import {useEffect,useState} from "react";
import type {Locale} from "@/lib/locales";
const copy:Record<Locale,string[]>={nl:["Nieuw wachtwoord","Nieuw wachtwoord","Herhaal wachtwoord","Minimaal 8 tekens: letters + 1 cijfer + 1 speciaal teken.","De wachtwoorden komen niet overeen.","Even geduld…","Wachtwoord opslaan →","Je wachtwoord is gewijzigd. Je wordt automatisch naar je dashboard gestuurd.","Er ging iets mis. Probeer het opnieuw.","Deze resetlink is ongeldig of ontbreekt."],en:["New password","New password","Repeat password","At least 8 characters: letters + 1 number + 1 special character.","The passwords do not match.","Please wait…","Save password →","Your password has been changed. You will be taken to your dashboard automatically.","Something went wrong. Please try again.","This reset link is invalid or missing."],de:["Neues Passwort","Neues Passwort","Passwort wiederholen","Mindestens 8 Zeichen: Buchstaben + 1 Zahl + 1 Sonderzeichen.","Die Passwörter stimmen nicht überein.","Bitte warten…","Passwort speichern →","Dein Passwort wurde geändert. Du wirst automatisch zu deinem Dashboard weitergeleitet.","Etwas ist schiefgelaufen. Bitte versuche es erneut.","Dieser Reset-Link ist ungültig oder fehlt."],fr:["Nouveau mot de passe","Nouveau mot de passe","Répéter le mot de passe","Au moins 8 caractères : lettres + 1 chiffre + 1 caractère spécial.","Les mots de passe ne correspondent pas.","Veuillez patienter…","Enregistrer le mot de passe →","Votre mot de passe a été modifié. Vous allez être redirigé vers votre tableau de bord.","Une erreur s’est produite. Réessayez.","Ce lien de réinitialisation est invalide ou manquant."],it:["Nuova password","Nuova password","Ripeti password","Almeno 8 caratteri: lettere + 1 numero + 1 carattere speciale.","Le password non corrispondono.","Attendi…","Salva password →","La password è stata modificata. Verrai reindirizzato automaticamente alla dashboard.","Si è verificato un errore. Riprova.","Questo link di reimpostazione non è valido o manca."],es:["Nueva contraseña","Nueva contraseña","Repetir contraseña","Mínimo 8 caracteres: letras + 1 número + 1 carácter especial.","Las contraseñas no coinciden.","Espera…","Guardar contraseña →","Tu contraseña ha sido cambiada. Serás redirigido automáticamente al panel.","Algo salió mal. Inténtalo de nuevo.","Este enlace de restablecimiento no es válido o falta."]};
export default function ResetPassword(){
 const[token,setToken]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false),[language,setLanguage]=useState<Locale>("nl");
 useEffect(()=>{const p=new URLSearchParams(location.search);setToken(p.get("token")||"");const l=p.get("lang") as Locale|null;if(l&&l in copy)setLanguage(l)},[]);const t=copy[language];
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(password!==confirm){setError(t[4]);return}if(!(password.length>=8&&/[A-Za-z]/.test(password)&&/\d/.test(password)&&/[^A-Za-z0-9]/.test(password))){setError(t[3]);return}setBusy(true);try{const r=await fetch("/api/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password,language})});const d=await r.json();if(!r.ok){setError(d.error||t[8]);return}setDone(true);setTimeout(()=>location.replace("/dashboard"),900)}catch{setError(t[8])}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#0B1220] px-5 py-12 text-white" lang={language}><div className="mx-auto max-w-md"><a href={"/"+language} className="text-lg font-bold">RankFix <span className="text-emerald-300">AI</span></a><div className="mt-10 rounded-3xl border border-white/10 bg-white/[0.04] p-7"><h1 className="text-3xl font-black">{t[0]}</h1>{done?<div className="mt-6 rounded-xl bg-emerald-500/10 p-4 text-sm text-emerald-200">{t[7]}</div>:<form onSubmit={submit} className="mt-7 space-y-4"><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={t[1]} autoComplete="new-password" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><input required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder={t[2]} autoComplete="new-password" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><p className="text-xs text-slate-400">{t[3]}</p>{!token&&<div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{t[9]}</div>}{error&&<div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}<button disabled={busy||!token} className="w-full rounded-xl bg-white px-4 py-3 font-bold text-slate-950 disabled:opacity-50">{busy?t[5]:t[6]}</button></form>}</div></div></main>
}