"use client";
import {useEffect,useState} from "react";
import DashboardNav from "../nav";
import type {Locale} from "@/lib/locales";
import "../dashboard.css";

type Property={siteUrl:string;permissionLevel:string;selected?:boolean};
type PropertiesResponse={connected:boolean;properties:Property[];selectedSiteUrl?:string|null;error?:string};
type MetricRow={name:string;clicks:number;impressions:number;ctr:number;position:number};
type Performance={siteUrl:string;startDate:string;endDate:string;summary:{clicks:number;impressions:number;ctr:number;position:number};queries:MetricRow[];pages:MetricRow[];syncedAt:string};

const copy={
nl:{title:"Google Search Console",sub:"Echte Google-prestatiedata voor je geselecteerde website.",connect:"Google koppelen",choose:"Kies een property",save:"Opslaan",none:"Nog geen koppeling.",readonly:"RankFix vraagt alleen leesrechten. Je Search Console-instellingen worden niet gewijzigd.",saved:"Opgeslagen.",failed:"Opslaan mislukt.",saving:"Bezig…",loading:"Google-data laden…",refresh:"Vernieuwen",clicks:"Klikken",impressions:"Vertoningen",ctr:"CTR",position:"Gem. positie",period:"Laatste 28 dagen",queries:"Beste zoekopdrachten",pages:"Beste pagina’s",empty:"Nog geen Search Console-data voor deze periode.",query:"Zoekopdracht",page:"Pagina",error:"Google-data kon niet worden geladen."},
en:{title:"Google Search Console",sub:"Real Google performance data for your selected website.",connect:"Connect Google",choose:"Choose a property",save:"Save",none:"Not connected yet.",readonly:"RankFix requests read-only access. Your Search Console settings are not changed.",saved:"Saved.",failed:"Could not save.",saving:"Saving…",loading:"Loading Google data…",refresh:"Refresh",clicks:"Clicks",impressions:"Impressions",ctr:"CTR",position:"Avg. position",period:"Last 28 days",queries:"Top queries",pages:"Top pages",empty:"No Search Console data for this period yet.",query:"Query",page:"Page",error:"Could not load Google data."},
de:{title:"Google Search Console",sub:"Echte Google-Leistungsdaten für deine ausgewählte Website.",connect:"Google verbinden",choose:"Property wählen",save:"Speichern",none:"Noch nicht verbunden.",readonly:"RankFix fordert nur Lesezugriff an. Deine Search-Console-Einstellungen werden nicht geändert.",saved:"Gespeichert.",failed:"Speichern fehlgeschlagen.",saving:"Speichern…",loading:"Google-Daten werden geladen…",refresh:"Aktualisieren",clicks:"Klicks",impressions:"Impressionen",ctr:"CTR",position:"Ø Position",period:"Letzte 28 Tage",queries:"Top-Suchanfragen",pages:"Top-Seiten",empty:"Noch keine Search-Console-Daten für diesen Zeitraum.",query:"Suchanfrage",page:"Seite",error:"Google-Daten konnten nicht geladen werden."},
fr:{title:"Google Search Console",sub:"Données de performance Google réelles pour le site sélectionné.",connect:"Connecter Google",choose:"Choisir une propriété",save:"Enregistrer",none:"Pas encore connecté.",readonly:"RankFix demande uniquement un accès en lecture. Vos paramètres Search Console ne sont pas modifiés.",saved:"Enregistré.",failed:"Échec de l’enregistrement.",saving:"Enregistrement…",loading:"Chargement des données Google…",refresh:"Actualiser",clicks:"Clics",impressions:"Impressions",ctr:"CTR",position:"Position moy.",period:"28 derniers jours",queries:"Meilleures requêtes",pages:"Meilleures pages",empty:"Aucune donnée Search Console pour cette période.",query:"Requête",page:"Page",error:"Impossible de charger les données Google."},
it:{title:"Google Search Console",sub:"Dati reali sulle prestazioni Google per il sito selezionato.",connect:"Collega Google",choose:"Scegli una proprietà",save:"Salva",none:"Non ancora collegato.",readonly:"RankFix richiede solo accesso in lettura. Le impostazioni Search Console non vengono modificate.",saved:"Salvato.",failed:"Salvataggio non riuscito.",saving:"Salvataggio…",loading:"Caricamento dati Google…",refresh:"Aggiorna",clicks:"Clic",impressions:"Impressioni",ctr:"CTR",position:"Posizione media",period:"Ultimi 28 giorni",queries:"Query principali",pages:"Pagine principali",empty:"Nessun dato Search Console per questo periodo.",query:"Query",page:"Pagina",error:"Impossibile caricare i dati Google."},
es:{title:"Google Search Console",sub:"Datos reales de rendimiento de Google para el sitio seleccionado.",connect:"Conectar Google",choose:"Elegir propiedad",save:"Guardar",none:"Aún no conectado.",readonly:"RankFix solicita solo acceso de lectura. No modifica la configuración de Search Console.",saved:"Guardado.",failed:"No se pudo guardar.",saving:"Guardando…",loading:"Cargando datos de Google…",refresh:"Actualizar",clicks:"Clics",impressions:"Impresiones",ctr:"CTR",position:"Posición media",period:"Últimos 28 días",queries:"Consultas principales",pages:"Páginas principales",empty:"Aún no hay datos de Search Console para este período.",query:"Consulta",page:"Página",error:"No se pudieron cargar los datos de Google."}
} as const;

export default function Page(){
 const[l,setL]=useState<Locale>("nl");const[data,setData]=useState<PropertiesResponse|null>(null);const[selected,setSelected]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[perf,setPerf]=useState<Performance|null>(null);const[perfBusy,setPerfBusy]=useState(false);const[perfError,setPerfError]=useState("");
 const t=copy[l];
 async function loadPerformance(){setPerfBusy(true);setPerfError("");try{const r=await fetch("/api/google/search-console/performance",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d?.error||t.error);setPerf(d)}catch(cause){setPerf(null);setPerfError(cause instanceof Error?cause.message:t.error)}finally{setPerfBusy(false)}}
 useEffect(()=>{fetch("/api/account/language").then(r=>r.ok?r.json():null).then(d=>{if(d?.language)setL(d.language)});fetch("/api/google/search-console/properties",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error||"load");return d as PropertiesResponse}).then(d=>{setData(d);const initial=d.selectedSiteUrl||(d.properties?.length===1?d.properties[0].siteUrl:"");setSelected(initial);if(d.selectedSiteUrl)void loadPerformance()}).catch(()=>setData({connected:false,properties:[]}))},[]);
 async function save(){const p=data?.properties?.find(x=>x.siteUrl===selected);if(!p||busy)return;setBusy(true);setMessage("");try{const r=await fetch("/api/google/search-console/properties",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({siteUrl:p.siteUrl,permissionLevel:p.permissionLevel})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||t.failed);setData(current=>current?{...current,selectedSiteUrl:p.siteUrl,properties:current.properties.map(x=>({...x,selected:x.siteUrl===p.siteUrl}))}:current);setSelected(p.siteUrl);setMessage(t.saved);await loadPerformance()}catch(cause){setMessage(cause instanceof Error?cause.message:t.failed)}finally{setBusy(false)}}
 const metric=(v:number,type?:"ctr"|"position")=>type==="ctr"?(v*100).toFixed(1)+"%":type==="position"?v.toFixed(1):Math.round(v).toLocaleString(l);
 return <main className="rf-page" lang={l}><div className="rf-shell"><header className="rf-header"><a href="/dashboard" className="rf-brand">RankFix <span>AI</span></a></header><DashboardNav/><div className="rf-body"><div className="rf-heading"><h1>{t.title}</h1><p>{t.sub}</p></div><section className="rounded-2xl border border-blue-400/20 bg-blue-400/[0.06] p-5"><p className="text-sm text-slate-400">{t.readonly}</p>{!data?.connected?<><p className="mt-4 text-slate-300">{t.none}</p><a className="rf-primary-link mt-4 inline-flex" href="/api/google/search-console/connect">{t.connect}</a></>:<div className="mt-4"><label className="block text-sm font-bold text-white">{t.choose}</label><select className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 p-3" value={selected} onChange={e=>{setSelected(e.target.value);setMessage("")}}><option value="">—</option>{data.properties?.map(p=><option key={p.siteUrl} value={p.siteUrl}>{p.siteUrl}</option>)}</select><button type="button" className="rf-primary-link mt-3" disabled={!selected||busy} onClick={save}>{busy?t.saving:t.save}</button>{message&&<p className="mt-3 text-sm text-slate-300" role="status">{message}</p>}</div>}</section>
 {data?.selectedSiteUrl&&<section className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-white">{t.period}</h2>{perf&&<p className="text-sm text-slate-400">{perf.startDate} – {perf.endDate}</p>}</div><button type="button" className="rf-primary-link" onClick={()=>void loadPerformance()} disabled={perfBusy}>{perfBusy?t.loading:t.refresh}</button></div>{perfError&&<p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{perfError}</p>}{perf&&<><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{[[t.clicks,metric(perf.summary.clicks)],[t.impressions,metric(perf.summary.impressions)],[t.ctr,metric(perf.summary.ctr,"ctr")],[t.position,metric(perf.summary.position,"position")]].map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="text-sm text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold text-white">{value}</p></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><MetricTable title={t.queries} first={t.query} rows={perf.queries} t={t}/><MetricTable title={t.pages} first={t.page} rows={perf.pages} t={t}/></div></>}</section>}</div></div></main>
}
function MetricTable({title,first,rows,t}:{title:string;first:string;rows:MetricRow[];t:(typeof copy)[Locale]}){return <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.04]"><h3 className="p-4 text-lg font-bold text-white">{title}</h3>{rows.length===0?<p className="px-4 pb-4 text-sm text-slate-400">{t.empty}</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-slate-400"><tr><th className="px-4 py-3">{first}</th><th className="px-3 py-3">{t.clicks}</th><th className="px-3 py-3">{t.impressions}</th><th className="px-3 py-3">{t.position}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.name+i} className="border-t border-white/10"><td className="max-w-[260px] truncate px-4 py-3 text-white" title={r.name}>{r.name}</td><td className="px-3 py-3">{Math.round(r.clicks)}</td><td className="px-3 py-3">{Math.round(r.impressions)}</td><td className="px-3 py-3">{r.position.toFixed(1)}</td></tr>)}</tbody></table></div>}</div>}
