"use client";
import { useEffect,useState } from "react";
import DashboardNav from "../nav";
import "../dashboard.css";

type Review={rating:number;review_text:string;company_name?:string;website?:string;status:string};
export default function ReviewsPage(){
 const [review,setReview]=useState<Review|null>(null),[rating,setRating]=useState(5),[text,setText]=useState(""),[company,setCompany]=useState(""),[website,setWebsite]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/reviews",{cache:"no-store"}).then(async r=>{if(r.status===401){location.href="/account";return null}return r.json()}).then(d=>{if(d?.review){setReview(d.review);setRating(d.review.rating);setText(d.review.review_text);setCompany(d.review.company_name||"");setWebsite(d.review.website||"")}})},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/reviews",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({rating,reviewText:text,companyName:company,website})});const d=await r.json();setBusy(false);setMessage(d.message||d.error||"");if(r.ok)setReview(d.review)}
 async function remove(){if(!confirm("Wil je je review verwijderen?"))return;await fetch("/api/reviews",{method:"DELETE"});setReview(null);setText("");setCompany("");setWebsite("");setMessage("Je review is verwijderd.")}
 return <main className="rf-page"><div className="rf-shell"><header className="rf-header"><a href="/dashboard" className="rf-brand">RankFix <span>AI</span></a><a href="/dashboard/more" className="rf-back">← Meer</a></header><DashboardNav current={5}/><div className="rf-body"><div className="rf-heading"><h1>Review geven</h1><p>Alleen ingelogde RankFix-klanten kunnen een review plaatsen. Na controle kan je review als geverifieerde klantreview op de RankFix-site verschijnen.</p></div><form onSubmit={save} className="rf-review-form"><section className="rf-card"><label>Jouw beoordeling</label><div className="rf-stars">{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setRating(n)} aria-label={n+" sterren"} className={n<=rating?"active":""}>★</button>)}</div><label>Jouw ervaring<textarea value={text} onChange={e=>setText(e.target.value)} minLength={10} maxLength={1500} required rows={6} placeholder="Vertel wat RankFix voor je website of webshop heeft geholpen."/></label><label>Bedrijfsnaam <small>(optioneel)</small><input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Website <small>(optioneel)</small><input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://..."/></label><button className="rf-primary" disabled={busy}>{busy?"Opslaan…":review?"Review bijwerken":"Review versturen"}</button>{review&&<p className="rf-review-status">Status: <b>{review.status==="APPROVED"?"Goedgekeurd":review.status==="REJECTED"?"Niet gepubliceerd":"Wacht op controle"}</b></p>}{message&&<p className="rf-notice">{message}</p>}{review&&<button type="button" className="rf-danger-button" onClick={remove}>Review verwijderen</button>}</section></form></div></div></main>
}