"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
import type {Locale} from "@/lib/locales";
import DashboardNav from "../nav";
import "../dashboard.css";

type Site={url:string;scores:{overall:number;technical:number;onPage:number;content:number;structuredData:number;internalLinks:number};issues:number;pages:number};
type Result={website:Site;competitor:Site;opportunities:Array<{rule_id:string;title:string;severity:string;recommendation:string}>;notice?:string;scope?:{mode:string;website?:string;competitor?:string}};

const ui:Record<Locale,string[]>={nl:["Concurrent Scan","Vergelijk je website met een concurrent en ontdek concrete kansen.","Jouw website","Concurrent","Vergelijken…","Vergelijk websites","Vergelijking","pagina's gecontroleerd","aandachtspunten op jouw site.","Scores naast elkaar","jij / concurrent","Kansen voor jouw website","Geen unieke kansen gevonden in deze quick scan.","Vergelijking mislukt.","Totaal","Techniek","On-page","Content","Structured data","Interne links","tegenover"],en:["Competitor Scan","Compare your website with a competitor and discover concrete opportunities.","Your website","Competitor","Comparing…","Compare websites","Comparison","pages checked","issues on your site.","Scores side by side","you / competitor","Opportunities for your website","No unique opportunities found in this quick scan.","Comparison failed.","Overall","Technical","On-page","Content","Structured data","Internal links","versus"],de:["Konkurrenz-Scan","Vergleiche deine Website mit einem Konkurrenten und finde konkrete Chancen.","Deine Website","Konkurrent","Vergleichen…","Websites vergleichen","Vergleich","Seiten geprüft","Probleme auf deiner Website.","Scores im Vergleich","du / Konkurrent","Chancen für deine Website","Keine einzigartigen Chancen in diesem Quick-Scan gefunden.","Vergleich fehlgeschlagen.","Gesamt","Technik","On-page","Inhalt","Strukturierte Daten","Interne Links","gegenüber"],fr:["Analyse concurrentielle","Comparez votre site à un concurrent et découvrez des opportunités concrètes.","Votre site","Concurrent","Comparaison…","Comparer les sites","Comparaison","pages contrôlées","points à améliorer sur votre site.","Scores côte à côte","vous / concurrent","Opportunités pour votre site","Aucune opportunité unique trouvée dans cette analyse rapide.","La comparaison a échoué.","Global","Technique","On-page","Contenu","Données structurées","Liens internes","contre"],it:["Analisi concorrente","Confronta il tuo sito con un concorrente e scopri opportunità concrete.","Il tuo sito","Concorrente","Confronto…","Confronta siti","Confronto","pagine controllate","problemi sul tuo sito.","Punteggi a confronto","tu / concorrente","Opportunità per il tuo sito","Nessuna opportunità unica trovata in questa scansione rapida.","Confronto non riuscito.","Totale","Tecnica","On-page","Contenuto","Dati strutturati","Link interni","rispetto a"],es:["Análisis de competencia","Compara tu web con un competidor y descubre oportunidades concretas.","Tu web","Competidor","Comparando…","Comparar webs","Comparación","páginas revisadas","problemas en tu web.","Puntuaciones comparadas","tú / competidor","Oportunidades para tu web","No se encontraron oportunidades únicas en este análisis rápido.","La comparación ha fallado.","Total","Técnica","On-page","Contenido","Datos estructurados","Enlaces internos","frente a"]};
export default function CompetitorPage(){
 const params=useSearchParams(); const[language,setLanguage]=useState<Locale>("nl"); const[website,setWebsite]=useState("");const[competitor,setCompetitor]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[result,setResult]=useState<Result|null>(null);const[plan,setPlan]=useState("free");
 useEffect(()=>{setWebsite(params.get("url")||"");fetch("/api/account/language").then(r=>r.ok?r.json():null).then(d=>{if(d?.language&&d.language in ui)setLanguage(d.language)}).catch(()=>{});fetch("/api/history",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>{if(d?.usage?.plan)setPlan(d.usage.plan)}).catch(()=>{})},[params]); const t=ui[language];
 async function run(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setResult(null);try{const r=await fetch("/api/competitor-scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({website,competitor,language})});const d=await r.json();if(!r.ok)throw new Error(d.error||t[13]);setResult(d)}catch(x){setError(x instanceof Error?x.message:t[13])}finally{setBusy(false)}}
 const rows:[string,keyof Site["scores"]][]=[[t[14],"overall"],[t[15],"technical"],[t[16],"onPage"],[t[17],"content"],[t[18],"structuredData"],[t[19],"internalLinks"]];
 return <main className="rf-page" lang={language}><div className="rf-shell"><header className="rf-header"><Link href="/" className="rf-brand" aria-label="RankFix AI home">RankFix <span>AI</span></Link></header><DashboardNav/><div className="rf-body">
  <div className="rf-heading"><h1>{t[0]}</h1><p>{t[1]}</p></div>
  {plan==="free"&&<section className="rf-plan-card"><div><span className="rf-eyebrow">Premium</span><h2>{language==="nl"?"Concurrentanalyse is een betaalde functie":language==="de"?"Konkurrenzanalyse ist eine kostenpflichtige Funktion":language==="fr"?"L’analyse concurrentielle est une fonction payante":language==="it"?"L’analisi concorrente è una funzione a pagamento":language==="es"?"El análisis de competencia es una función de pago":"Competitor analysis is a paid feature"}</h2></div><Link className="rf-primary-link" href="/#pricing">{language==="nl"?"Bekijk abonnementen":language==="de"?"Tarife ansehen":language==="fr"?"Voir les offres":language==="it"?"Vedi i piani":language==="es"?"Ver planes":"View plans"}</Link></section>}
  <section className="rf-dashboard-scan"><form onSubmit={run}><label>{t[2]}</label><input type="url" placeholder="https://jouwsite.nl" value={website} onChange={e=>setWebsite(e.target.value)} required/><label>{t[3]}</label><input type="url" placeholder="https://concurrent.nl" value={competitor} onChange={e=>setCompetitor(e.target.value)} required/><button className="rf-primary" disabled={busy||plan==="free"}>{busy?t[4]:t[5]}</button></form></section>
  {error&&<p className="rf-alert">{error}</p>}
  {result&&<><section className="rf-report"><div><span className="rf-eyebrow">{t[6]}</span><h2>{result.website.scores.overall}/100 {t[20]} {result.competitor.scores.overall}/100</h2><p>{result.website.pages} {t[7]} · {result.website.issues} {t[8]}</p>{result.notice&&<p className="mt-2 text-sm text-slate-400">{result.notice}</p>}</div></section>
  <section className="rf-report"><div style={{width:"100%"}}><h2>{t[9]}</h2>{rows.map(([label,key])=><p key={key}><strong>{label}</strong>: {result.website.scores[key]} / {result.competitor.scores[key]} <small>({t[10]})</small></p>)}</div></section>
  <section className="rf-report"><div><h2>{t[11]}</h2>{result.opportunities.length?result.opportunities.map(x=><div key={x.rule_id}><strong>{x.title}</strong><p>{x.recommendation}</p></div>):<p>{t[12]}</p>}</div></section>
  <section className="rf-card" style={{marginTop:16}}><span className="rf-eyebrow">{language==="nl"?"Jouw feedback":language==="de"?"Dein Feedback":language==="fr"?"Votre avis":language==="it"?"Il tuo feedback":language==="es"?"Tu opinión":"Your feedback"}</span><h2>{language==="nl"?"Was deze Concurrent Scan nuttig en klopte de vergelijking?":language==="de"?"War dieser Konkurrenz-Scan hilfreich und war der Vergleich korrekt?":language==="fr"?"Cette analyse concurrentielle était-elle utile et la comparaison correcte ?":language==="it"?"Questa analisi concorrente è stata utile e il confronto era corretto?":language==="es"?"¿Fue útil este análisis de competencia y fue correcta la comparación?":"Was this Competitor Scan useful and was the comparison accurate?"}</h2><p className="mt-2 text-sm text-slate-400">{language==="nl"?"Geef onderaan je review. Zo kunnen we zien of RankFix de juiste punten en kansen heeft gevonden.":language==="de"?"Gib uns deine Bewertung. So sehen wir, ob RankFix die richtigen Punkte und Chancen gefunden hat.":language==="fr"?"Donnez votre avis afin de nous aider à vérifier si RankFix a identifié les bons points et opportunités.":language==="it"?"Lascia una recensione per aiutarci a verificare se RankFix ha trovato i punti e le opportunità giusti.":language==="es"?"Deja una reseña para ayudarnos a comprobar si RankFix encontró los puntos y oportunidades correctos.":"Leave a review to help us verify whether RankFix found the right issues and opportunities."}</p><Link className="rf-primary-link mt-4 inline-flex" href={`/dashboard/reviews?website=${encodeURIComponent(website)}`}>{language==="nl"?"Review geven":language==="de"?"Bewertung abgeben":language==="fr"?"Donner un avis":language==="it"?"Lascia una recensione":language==="es"?"Dejar reseña":"Leave a review"} →</Link></section></>}
 </div></div></main>
}
