"use client";
import {useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
import type {Locale} from "@/lib/locales";
import DashboardNav from "../nav";
import "../dashboard.css";

type Site={url:string;scores:{overall:number;technical:number;onPage:number;content:number;structuredData:number;internalLinks:number};issues:number;pages:number};
type Result={website:Site;competitor:Site;opportunities:Array<{rule_id:string;title:string;severity:string;recommendation:string}>};

const ui:Record<Locale,string[]>={nl:["Concurrent Scan","Vergelijk je website met een concurrent en ontdek concrete kansen.","Jouw website","Concurrent","Vergelijken…","Vergelijk websites","Vergelijking","pagina's gecontroleerd","aandachtspunten op jouw site.","Scores naast elkaar","jij / concurrent","Kansen voor jouw website","Geen unieke kansen gevonden in deze quick scan."],en:["Competitor Scan","Compare your website with a competitor and discover concrete opportunities.","Your website","Competitor","Comparing…","Compare websites","Comparison","pages checked","issues on your site.","Scores side by side","you / competitor","Opportunities for your website","No unique opportunities found in this quick scan."],de:["Konkurrenz-Scan","Vergleiche deine Website mit einem Konkurrenten und finde konkrete Chancen.","Deine Website","Konkurrent","Vergleichen…","Websites vergleichen","Vergleich","Seiten geprüft","Probleme auf deiner Website.","Scores im Vergleich","du / Konkurrent","Chancen für deine Website","Keine einzigartigen Chancen in diesem Quick-Scan gefunden."],fr:["Analyse concurrentielle","Comparez votre site à un concurrent et découvrez des opportunités concrètes.","Votre site","Concurrent","Comparaison…","Comparer les sites","Comparaison","pages contrôlées","points à améliorer sur votre site.","Scores côte à côte","vous / concurrent","Opportunités pour votre site","Aucune opportunité unique trouvée dans cette analyse rapide."],it:["Analisi concorrente","Confronta il tuo sito con un concorrente e scopri opportunità concrete.","Il tuo sito","Concorrente","Confronto…","Confronta siti","Confronto","pagine controllate","problemi sul tuo sito.","Punteggi a confronto","tu / concorrente","Opportunità per il tuo sito","Nessuna opportunità unica trovata in questa scansione rapida."],es:["Análisis de competencia","Compara tu web con un competidor y descubre oportunidades concretas.","Tu web","Competidor","Comparando…","Comparar webs","Comparación","páginas revisadas","problemas en tu web.","Puntuaciones comparadas","tú / competidor","Oportunidades para tu web","No se encontraron oportunidades únicas en este análisis rápido."]};
export default function CompetitorPage(){
 const params=useSearchParams(); const[language,setLanguage]=useState<Locale>("nl"); const[website,setWebsite]=useState("");const[competitor,setCompetitor]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[result,setResult]=useState<Result|null>(null);
 useEffect(()=>{setWebsite(params.get("url")||"");fetch("/api/account/language").then(r=>r.ok?r.json():null).then(d=>{if(d?.language&&d.language in ui)setLanguage(d.language)}).catch(()=>{})},[params]); const t=ui[language];
 async function run(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setResult(null);try{const r=await fetch("/api/competitor-scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({website,competitor})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Vergelijking mislukt.");setResult(d)}catch(x){setError(x instanceof Error?x.message:"Vergelijking mislukt.")}finally{setBusy(false)}}
 const rows:[string,keyof Site["scores"]][]=[["Overall","overall"],["Techniek","technical"],["On-page","onPage"],["Content","content"],["Structured data","structuredData"],["Interne links","internalLinks"]];
 return <main className="rf-page" lang={language}><div className="rf-shell"><header className="rf-header"><a href="/" className="rf-brand" aria-label="RankFix AI home">RankFix <span>AI</span></a></header><DashboardNav/><div className="rf-body">
  <div className="rf-heading"><h1>{t[0]}</h1><p>{t[1]}</p></div>
  <section className="rf-dashboard-scan"><form onSubmit={run}><label>{t[2]}</label><input type="url" placeholder="https://jouwsite.nl" value={website} onChange={e=>setWebsite(e.target.value)} required/><label>{t[3]}</label><input type="url" placeholder="https://concurrent.nl" value={competitor} onChange={e=>setCompetitor(e.target.value)} required/><button className="rf-primary" disabled={busy}>{busy?t[4]:t[5]}</button></form></section>
  {error&&<p className="rf-alert">{error}</p>}
  {result&&<><section className="rf-report"><div><span className="rf-eyebrow">{t[6]}</span><h2>{result.website.scores.overall}/100 tegenover {result.competitor.scores.overall}/100</h2><p>{result.website.pages} {t[7]} · {result.website.issues} {t[8]}</p></div></section>
  <section className="rf-report"><div style={{width:"100%"}}><h2>{t[9]}</h2>{rows.map(([label,key])=><p key={key}><strong>{label}</strong>: {result.website.scores[key]} / {result.competitor.scores[key]} <small>({t[10]})</small></p>)}</div></section>
  <section className="rf-report"><div><h2>{t[11]}</h2>{result.opportunities.length?result.opportunities.map(x=><div key={x.rule_id}><strong>{x.title}</strong><p>{x.recommendation}</p></div>):<p>{t[12]}</p>}</div></section></>}
 </div></div></main>
}
